function traduci(){

var parola = document.getElementById("parola").value;
parola = parola.toLowerCase();
parola = parola.split(' ').join('');
var traduzione = '';


if(parola == 'abbandonare'){traduzione = ''; significati = ''}
else if(parola == 'abbandonato'){traduzione = 'egla'; significati = ''}
else if(parola == 'abbandono'){traduzione = 'awarthad'; significati = ''}
else if(parola == 'abbigliare'){traduzione = 'hamma'; significati = ''}
else if(parola == 'abbigliare'){traduzione = 'hammannen'; significati = ''}
else if(parola == 'abbondante'){traduzione = 'ovrol'; significati = 'che è ricco'}
else if(parola == 'abbondanza'){traduzione = 'ovrad'; significati = 'inteso anche come ricchezza'}
else if(parola == 'abbondare'){traduzione = 'ovra'; significati = 'essere ricco'}
else if(parola == 'abbondato'){traduzione = 'ovrannen'; significati = 'stato ricco'}
else if(parola == 'abigliamento'){traduzione = 'hammhad'; significati = ''}
else if(parola == 'abilità'){traduzione = 'curu'; significati = 'sinonimo di destrezza'}
else if(parola == 'abisso'){traduzione = 'iai'; significati = 'sinonimo di vuoto'}
else if(parola == 'abitare'){traduzione = 'quono'; significati = ''}
else if(parola == 'abito'){traduzione = 'haew'; significati = ''}
else if(parola == 'aborrire'){traduzione = 'fuia'; significati = 'sentire disgusto per'}
else if(parola == 'aborrito'){traduzione = 'fiuannen'; significati = ''}
else if(parola == 'accerchiamento'){traduzione = 'peled'; significati = ''}
else if(parola == 'acqua'){traduzione = 'belah'; significati = ''}
else if(parola == 'acqua'){traduzione = 'nen'; significati = ''}
else if(parola == 'acquoso'){traduzione = 'nenui'; significati = ''}
else if(parola == 'addio'){traduzione = 'mondor'; significati = ''}
else if(parola == 'afferrare'){traduzione = 'mab'; significati = 'sinonimi: prendere, portare'}
else if(parola == 'afferrato'){traduzione = 'mammen'; significati = 'sinonimi: preso, portato via con la forza'}
else if(parola == 'affliggere'){traduzione = 'presta'; significati = 'sinonimo: preoccupare'}
else if(parola == 'afflizione'){traduzione = 'prestad'; significati = ''}
else if(parola == 'agnello'){traduzione = 'waldeaz'; significati = ''}
else if(parola == 'agrifoglio'){traduzione = 'ereg'; significati = ''}
else if(parola == 'aguzzo'){traduzione = 'erui'; significati = ''}
else if(parola == 'albero'){traduzione = 'galadh'; significati = ''}
else if(parola == 'allontanamento'){traduzione = 'mistad'; significati = ''}
else if(parola == 'allontanarsi'){traduzione = 'mista'; significati = ''}
else if(parola == 'allontanato'){traduzione = 'mistannen'; significati = ''}
else if(parola == 'alto'){traduzione = 'tond'; significati = ''}
else if(parola == 'alzare'){traduzione = 'eria'; significati = ''}
else if(parola == 'amante'){traduzione = 'melel'; significati = ''}
else if(parola == 'amare'){traduzione = 'mel'; significati = ''}
else if(parola == 'amare'){traduzione = 'nakoo'; significati = ''}
else if(parola == 'amato'){traduzione = 'mellen'; significati = ''}
else if(parola == 'amico'){traduzione = 'mellon'; significati = ''}
else if(parola == 'ammazzare'){traduzione = 'dag'; significati = ''}
else if(parola == 'ammicco'){traduzione = 'dag'; significati = ''}
else if(parola == 'amore'){traduzione = 'land'; significati = ''}
else if(parola == 'amore'){traduzione = 'nak'; significati = ''}
else if(parola == 'ampio'){traduzione = 'laind'; significati = ''}
else if(parola == 'andante'){traduzione = 'badel'; significati = ''}
else if(parola == 'andare'){traduzione = 'bad'; significati = ''}
else if(parola == 'andare'){traduzione = 'tahnars'; significati = ''}
else if(parola == 'andato'){traduzione = 'bannen'; significati = ''}
else if(parola == 'anello'){traduzione = 'selunioh'; significati = ''}
else if(parola == 'animale'){traduzione = 'lavan'; significati = 'termine usato per tutti gli animali (tranne rettili e insetti)'}
else if(parola == 'anno'){traduzione = 'idhrin'; significati = ''}
else if(parola == 'antipatico'){traduzione = 'rabikth'; significati = ''}
else if(parola == 'aperto'){traduzione = 'edrannen'; significati = ''}
else if(parola == 'aperto'){traduzione = 'medh'; significati = ''}
else if(parola == 'apertura'){traduzione = 'edrad'; significati = ''}
else if(parola == 'apparire'){traduzione = 'thia'; significati = ''}
else if(parola == 'apparso'){traduzione = 'thiannen'; significati = ''}
else if(parola == 'appendere'){traduzione = 'glinga'; significati = ''}
else if(parola == 'appeso'){traduzione = 'pennen'; significati = ''}
else if(parola == 'appuntito'){traduzione = 'laeg'; significati = ''}
else if(parola == 'aprente'){traduzione = 'edriol'; significati = ''}
else if(parola == 'aprire'){traduzione = 'edra'; significati = ''}
else if(parola == 'aquila'){traduzione = 'thoron'; significati = ''}
else if(parola == 'arco'){traduzione = 'peng'; significati = ''}
else if(parola == 'arco'){traduzione = 'zeframh'; significati = ''}
else if(parola == 'ardente'){traduzione = 'lachol'; significati = ''}
else if(parola == 'ardimento'){traduzione = 'berthad'; significati = ''}
else if(parola == 'ardimentoso'){traduzione = 'berthir'; significati = ''}
else if(parola == 'ardito'){traduzione = 'beren'; significati = ''}
else if(parola == 'argentato'){traduzione = 'celebrin'; significati = ''}
else if(parola == 'argento'){traduzione = 'celeb'; significati = ''}
else if(parola == 'argento'){traduzione = 'giltha'; significati = ''}
else if(parola == 'aria'){traduzione = 'erash'; significati = ''}
else if(parola == 'aria'){traduzione = 'gwelw'; significati = ''}
else if(parola == 'arma'){traduzione = 'birel'; significati = ''}
else if(parola == 'armatura'){traduzione = 'sisko'; significati = ''}
else if(parola == 'armistizio'){traduzione = 'gothwilm'; significati = ''}
else if(parola == 'arpa'){traduzione = 'gannel'; significati = ''}
else if(parola == 'arrestare'){traduzione = 'nuitha'; significati = ''}
else if(parola == 'arrestato'){traduzione = 'miuthannen'; significati = ''}
else if(parola == 'arresto'){traduzione = 'nuithad'; significati = ''}
else if(parola == 'arso'){traduzione = 'lachannen'; significati = ''}
else if(parola == 'articolo da scambiare'){traduzione = 'bach'; significati = ''}
else if(parola == 'ascesa'){traduzione = 'orthad'; significati = ''}
else if(parola == 'ascia'){traduzione = 'braoh'; significati = ''}
else if(parola == 'ascia'){traduzione = 'hathol'; significati = ''}
else if(parola == 'ascoltante'){traduzione = 'lastol'; significati = ''}
else if(parola == 'ascoltare'){traduzione = 'lasta'; significati = ''}
else if(parola == 'ascoltato'){traduzione = 'lastannen'; significati = ''}
else if(parola == 'ascoltatore'){traduzione = 'lathron'; significati = ''}
else if(parola == 'ascolto'){traduzione = 'lastad'; significati = ''}
else if(parola == 'asino'){traduzione = 'atit'; significati = ''}
else if(parola == 'aspettare'){traduzione = 'dartha'; significati = ''}
else if(parola == 'aspettato'){traduzione = 'darthannen'; significati = ''}
else if(parola == 'assassino'){traduzione = 'dagir'; significati = ''}
else if(parola == 'assassino'){traduzione = 'sahins'; significati = ''}
else if(parola == 'asse'){traduzione = 'pan';   significati = ''}
else if(parola == 'astuto'){traduzione = 'coru'; significati = ''}
else if(parola == 'attaccante'){traduzione = 'taehol'; significati = ''}
else if(parola == 'attaccare'){traduzione = 'lasher'; significati = ''}
else if(parola == 'attaccare'){traduzione = 'taetha'; significati = ''}
else if(parola == 'attaccato'){traduzione = 'taethannen'; significati = ''}
else if(parola == 'attacco'){traduzione = 'lash'; significati = ''}
else if(parola == 'attacco'){traduzione = 'taethad'; significati = ''}
else if(parola == 'attesa'){traduzione = 'darthad'; significati = ''}
else if(parola == 'attorno'){traduzione = 'os'; significati = ''}
else if(parola == 'attraversamento'){traduzione = 'trevaded'; significati = ''}
else if(parola == 'attraversante'){traduzione = 'athr'; significati = ''}
else if(parola == 'attraversare'){traduzione = 'athrennun'; significati = ''}
else if(parola == 'attraversato'){traduzione = 'atrhannen'; significati = ''}
else if(parola == 'attraverso'){traduzione = 'ath'; significati = ''}
else if(parola == 'audace'){traduzione = 'cand'; significati = ''}
else if(parola == 'avere'){traduzione = 'eram'; significati = ''}
else if(parola == 'avventuriero'){traduzione = 'helsior'; significati = ''}
else if(parola == 'avversione'){traduzione = 'deloth'; significati = ''}
else if(parola == 'avvicinamento'){traduzione = 'anglennad'; significati = ''}
else if(parola == 'avvicinarsi'){traduzione = 'anglenna'; significati = ''}
else if(parola == 'avvicinato'){traduzione = 'anglennen'; significati = ''}
else if(parola == 'azzurro'){traduzione = 'luin'; significati = ''}
else if(parola == 'bagnato'){traduzione = 'nin'; significati = ''}
else if(parola == 'balbettante'){traduzione = 'glavrol'; significati = ''}
else if(parola == 'balbettare'){traduzione = 'glavra'; significati = ''}
else if(parola == 'balbettato'){traduzione = 'glavrannen'; significati = ''}
else if(parola == 'balbettio'){traduzione = 'glavrad'; significati = ''}
else if(parola == 'bambino'){traduzione = 'hen'; significati = ''}
else if(parola == 'barba'){traduzione = 'fang'; significati = ''}
else if(parola == 'bardo'){traduzione = 'loniuth'; significati = ''}
else if(parola == 'bardo'){traduzione = 'shakaree'; significati = ''}
else if(parola == 'bastone'){traduzione = 'collek'; significati = ''}
else if(parola == 'battaglia'){traduzione = 'dagor'; significati = ''}
else if(parola == 'battere'){traduzione = 'dringa'; significati = ''}
else if(parola == 'battuta'){traduzione = 'dringad'; significati = ''}
else if(parola == 'battuto'){traduzione = 'dringannen'; significati = ''}
else if(parola == 'bello'){traduzione = 'bein'; significati = ''}
else if(parola == 'bello'){traduzione = 'gertan'; significati = ''}
else if(parola == 'bene'){traduzione = 'ik'; significati = ''}
else if(parola == 'bene'){traduzione = 'mae'; significati = ''}
else if(parola == 'benedire'){traduzione = 'ikwel'; significati = ''}
else if(parola == 'benedizione'){traduzione = 'ikwelnagako'; significati = ''}
else if(parola == 'bere'){traduzione = 'soga'; significati = ''}
else if(parola == 'bestemmiare'){traduzione = 'filkorn'; significati = ''}
else if(parola == 'betulla'){traduzione = 'neldor'; significati = ''}
else if(parola == 'bevuta'){traduzione = 'sogad'; significati = ''}
else if(parola == 'bevuto'){traduzione = 'sogannen'; significati = ''}
else if(parola == 'bianco'){traduzione = 'fein'; significati = ''}
else if(parola == 'birra'){traduzione = 'rakuk'; significati = ''}
else if(parola == 'bisogno'){traduzione = 'baur'; significati = ''}
else if(parola == 'blu'){traduzione = 'elu'; significati = ''}
else if(parola == 'bocca'){traduzione = 'krasysw'; significati = ''}
else if(parola == 'borchia'){traduzione = 'dolt'; significati = ''}
else if(parola == 'bordo'){traduzione = 'rain'; significati = ''}
else if(parola == 'bosco'){traduzione = 'rigults'; significati = ''}
else if(parola == 'bosco'){traduzione = 'taur'; significati = ''}
else if(parola == 'braccio'){traduzione = 'lichafr'; significati = ''}
else if(parola == 'braccio'){traduzione = 'ranc'; significati = ''}
else if(parola == 'brama'){traduzione = 'mael'; significati = ''}
else if(parola == 'brezza'){traduzione = 'gwileth'; significati = ''}
else if(parola == 'brillante'){traduzione = 'thiliol'; significati = ''}
else if(parola == 'brillantezza'){traduzione = 'thiliad'; significati = ''}
else if(parola == 'brillare'){traduzione = 'thilia'; significati = ''}
else if(parola == 'brillato'){traduzione = 'thiliannen'; significati = ''}
else if(parola == 'bruciare'){traduzione = 'folkha'; significati = ''}
else if(parola == 'brutto'){traduzione = 'gurtan'; significati = ''}
else if(parola == 'bucare'){traduzione = 'nasta'; significati = ''}
else if(parola == 'bucato'){traduzione = 'nastannen'; significati = ''}
else if(parola == 'buco'){traduzione = 'gass'; significati = ''}
else if(parola == 'bue'){traduzione = 'teukias'; significati = ''}
else if(parola == 'burrone'){traduzione = 'ress'; significati = ''}
else if(parola == 'caccia'){traduzione = 'rui'; significati = ''}
else if(parola == 'cacciare'){traduzione = 'fara'; significati = ''}
else if(parola == 'cacciato'){traduzione = 'farannen'; significati = ''}
else if(parola == 'cacciatore'){traduzione = 'faroth'; significati = ''}
else if(parola == 'cadavere'){traduzione = 'daen'; significati = ''}
else if(parola == 'cadente'){traduzione = 'dannol'; significati = ''}
else if(parola == 'cadere'){traduzione = 'danna'; significati = ''}
else if(parola == 'cadere'){traduzione = 'urrtz'; significati = ''}
else if(parola == 'caduta'){traduzione = 'dant'; significati = ''}
else if(parola == 'calcio'){traduzione = 'korkar'; significati = ''}
else if(parola == 'calcolare'){traduzione = 'genedia'; significati = ''}
else if(parola == 'calcolato'){traduzione = 'gendiannen'; significati = ''}
else if(parola == 'calcolo'){traduzione = 'genediad'; significati = ''}
else if(parola == 'calmo'){traduzione = 'vedek'; significati = ''}
else if(parola == 'calpestare'){traduzione = 'batha'; significati = ''}
else if(parola == 'calpestato'){traduzione = 'bathannen'; significati = ''}
else if(parola == 'calvo'){traduzione = 'rhudh'; significati = ''}
else if(parola == 'camminare'){traduzione = 'borkh'; significati = ''}
else if(parola == 'cammino'){traduzione = 'padad'; significati = ''}
else if(parola == 'campana'){traduzione = 'nell'; significati = ''}
else if(parola == 'campo'){traduzione = 'nand'; significati = ''}
else if(parola == 'cancello'){traduzione = 'annon'; significati = ''}
else if(parola == 'cane'){traduzione = 'hu'; significati = ''}
else if(parola == 'cane'){traduzione = 'ykohia'; significati = ''}
else if(parola == 'cantante'){traduzione = 'linnol'; significati = ''}
else if(parola == 'cantare'){traduzione = 'linna'; significati = ''}
else if(parola == 'cantato'){traduzione = 'linnen'; significati = ''}
else if(parola == 'capelli'){traduzione = 'fin'; significati = ''}
else if(parola == 'capire'){traduzione = 'hothron'; significati = ''}
else if(parola == 'capito'){traduzione = 'heniannen'; significati = ''}
else if(parola == 'cappio'){traduzione = 'niof'; significati = ''}
else if(parola == 'carne'){traduzione = 'rhaw'; significati = ''}
else if(parola == 'caro'){traduzione = 'mell'; significati = ''}
else if(parola == 'carro'){traduzione = 'rach'; significati = ''}
else if(parola == 'casa'){traduzione = 'bar'; significati = ''}
else if(parola == 'casa'){traduzione = 'quonos'; significati = ''}
else if(parola == 'castello'){traduzione = 'waldes'; significati = ''}
else if(parola == 'cattivo'){traduzione = 'faeg'; significati = ''}
else if(parola == 'cavalcare'){traduzione = 'jellah'; significati = ''}
else if(parola == 'cavaliere'){traduzione = 'rochon'; significati = ''}
else if(parola == 'cavallo'){traduzione = 'je'; significati = ''}
else if(parola == 'cavallo'){traduzione = 'roch'; significati = ''}
else if(parola == 'caverna'){traduzione = 'fela'; significati = ''}
else if(parola == 'caviglia'){traduzione = 'talrind'; significati = ''}
else if(parola == 'cavo'){traduzione = 'raudh'; significati = ''}
else if(parola == 'cenere'){traduzione = 'lith'; significati = ''}
else if(parola == 'cerchio'){traduzione = 'rind'; significati = ''}
else if(parola == 'che'){traduzione = 'jal'; significati = ''}
else if(parola == 'che'){traduzione = 'ots'; significati = ''}
else if(parola == 'chiamare'){traduzione = 'can'; significati = ''}
else if(parola == 'chiamata'){traduzione = 'estad'; significati = ''}
else if(parola == 'chiamato'){traduzione = 'cannen'; significati = ''}
else if(parola == 'chiaro'){traduzione = 'kherm'; significati = ''}
else if(parola == 'chiesa'){traduzione = 'haeged'; significati = ''}
else if(parola == 'chirico'){traduzione = 'charism'; significati = ''}
else if(parola == 'chiudere'){traduzione = 'sol'; significati = ''}
else if(parola == 'chiuso'){traduzione = 'dulkth'; significati = ''}
else if(parola == 'chiuso'){traduzione = 'sollen'; significati = ''}
else if(parola == 'ci'){traduzione = 'ic'; significati = ''}
else if(parola == 'ciao'){traduzione = 'kail'; significati = ''}
else if(parola == 'cibo'){traduzione = 'kolator'; significati = ''}
else if(parola == 'ciclo'){traduzione = 'anrann'; significati = ''}
else if(parola == 'cielo'){traduzione = 'hobas'; significati = ''}
else if(parola == 'cigno'){traduzione = 'alph'; significati = ''}
else if(parola == 'cima'){traduzione = 'caw'; significati = ''}
else if(parola == 'cinque'){traduzione = 'leben'; significati = ''}
else if(parola == 'cintura'){traduzione = 'iath'; significati = ''}
else if(parola == 'circondare'){traduzione = 'pel'; significati = ''}
else if(parola == 'circondato'){traduzione = 'pellen'; significati = ''}
else if(parola == 'città'){traduzione = 'gobel'; significati = ''}
else if(parola == 'clava'){traduzione = 'horan'; significati = ''}
else if(parola == 'colle'){traduzione = 'amon'; significati = ''}
else if(parola == 'collera'){traduzione = 'ruth'; significati = ''}
else if(parola == 'collina'){traduzione = 'tund'; significati = ''}
else if(parola == 'collo'){traduzione = 'cyveruas'; significati = ''}
else if(parola == 'collo'){traduzione = 'iaeth'; significati = ''}
else if(parola == 'colomba'){traduzione = 'cugu'; significati = ''}
else if(parola == 'colore'){traduzione = 'bashir'; significati = ''}
else if(parola == 'colpire'){traduzione = 'tamma'; significati = ''}
else if(parola == 'colpito'){traduzione = 'tammannen'; significati = ''}
else if(parola == 'colpo'){traduzione = 'tammad'; significati = ''}
else if(parola == 'coltellaccio'){traduzione = 'lang'; significati = ''}
else if(parola == 'combattente'){traduzione = 'maethol'; significati = ''}
else if(parola == 'combattere'){traduzione = 'maetha'; significati = ''}
else if(parola == 'combattuto'){traduzione = 'maethannen'; significati = ''}
else if(parola == 'come'){traduzione = 'ala'; significati = ''}
else if(parola == 'commerciante'){traduzione = 'bangir'; significati = ''}
else if(parola == 'commerciare'){traduzione = 'banga'; significati = ''}
else if(parola == 'commerciato'){traduzione = 'bangen'; significati = ''}
else if(parola == 'commercio'){traduzione = 'banghad'; significati = ''}
else if(parola == 'comprensione'){traduzione = 'heniad'; significati = ''}
else if(parola == 'con'){traduzione = 'na'; significati = ''}
else if(parola == 'concepimento'){traduzione = 'nauthad'; significati = ''}
else if(parola == 'concepire'){traduzione = 'nautha'; significati = ''}
else if(parola == 'concepito'){traduzione = 'nauthannen'; significati = ''}
else if(parola == 'condotto'){traduzione = 'tungen'; significati = ''}
else if(parola == 'conducente'){traduzione = 'togel'; significati = ''}
else if(parola == 'condurre'){traduzione = 'tog'; significati = ''}
else if(parola == 'conduttore'){traduzione = 'togir'; significati = ''}
else if(parola == 'conduzione'){traduzione = 'toged'; significati = ''}
else if(parola == 'confine'){traduzione = 'glan'; significati = ''}
else if(parola == 'conquista'){traduzione = 'orthored'; significati = ''}
else if(parola == 'conquistare'){traduzione = 'orthor'; significati = ''}
else if(parola == 'conquistato'){traduzione = 'orthornen'; significati = ''}
else if(parola == 'consanguineo'){traduzione = 'gwanur'; significati = ''}
else if(parola == 'consapevolezza'){traduzione = 'cuinad'; significati = ''}
else if(parola == 'conscio'){traduzione = 'cuinen'; significati = ''}
else if(parola == 'consolidamento'){traduzione = 'tangadad'; significati = ''}
else if(parola == 'consolidante'){traduzione = 'tangadol'; significati = ''}
else if(parola == 'consolidare'){traduzione = 'tangada'; significati = ''}
else if(parola == 'consolidato'){traduzione = 'tangadannen'; significati = ''}
else if(parola == 'contro'){traduzione = 'dan'; significati = ''}
else if(parola == 'coperto'){traduzione = 'tummen'; significati = ''}
else if(parola == 'copertura'){traduzione = 'tobad'; significati = ''}
else if(parola == 'coprente'){traduzione = 'tobol'; significati = ''}
else if(parola == 'coprire'){traduzione = 'toba'; significati = ''}
else if(parola == 'corazza'){traduzione = 'hoihokw'; significati = ''}
else if(parola == 'corno'){traduzione = 'ras'; significati = ''}
else if(parola == 'corona'){traduzione = 'ri'; significati = ''}
else if(parola == 'corpo'){traduzione = 'shjalluu'; significati = ''}
else if(parola == 'corrente'){traduzione = 'hoskiart'; significati = ''}
else if(parola == 'corrente'){traduzione = 'norel'; significati = ''}
else if(parola == 'correre'){traduzione = 'nebulh'; significati = ''}
else if(parola == 'correre'){traduzione = 'nor'; significati = ''}
else if(parola == 'corsa'){traduzione = 'nored'; significati = ''}
else if(parola == 'corso'){traduzione = 'nornen'; significati = 'utilizzato anche per dire corso d acqua'}
else if(parola == 'cortigiana'){traduzione = 'dennah'; significati = ''}
else if(parola == 'corto'){traduzione = 'thent'; significati = ''}
else if(parola == 'corvo'){traduzione = 'corch'; significati = ''}
else if(parola == 'costa'){traduzione = 'falas'; significati = ''}
else if(parola == 'costanza'){traduzione = 'bronweth'; significati = ''}
else if(parola == 'costruttore'){traduzione = 'tan'; significati = ''}
else if(parola == 'costruzione'){traduzione = 'cared'; significati = ''}
else if(parola == 'crepaccio'){traduzione = 'cil'; significati = ''}
else if(parola == 'crepaccio'){traduzione = 'cirith'; significati = ''}
else if(parola == 'crepuscolo'){traduzione = 'moth'; significati = ''}
else if(parola == 'crescere'){traduzione = 'gala'; significati = ''}
else if(parola == 'crescita'){traduzione = 'galad'; significati = ''}
else if(parola == 'cresciuto'){traduzione = 'gallen'; significati = ''}
else if(parola == 'crocefisso'){traduzione = 'keikor'; significati = ''}
else if(parola == 'crudele'){traduzione = 'balc'; significati = ''}
else if(parola == 'cuore'){traduzione = 'hun'; significati = ''}
else if(parola == 'cuscino'){traduzione = 'nedhu'; significati = ''}
else if(parola == 'da'){traduzione = 'o'; significati = ''}
else if(parola == 'dal'){traduzione = 'uin'; significati = ''}
else if(parola == 'dare'){traduzione = 'anna'; significati = ''}
else if(parola == 'dare'){traduzione = 'fayl'; significati = ''}
else if(parola == 'dato'){traduzione = 'onen'; significati = ''}
else if(parola == 'declinante'){traduzione = 'adlannol'; significati = ''}
else if(parola == 'declinare'){traduzione = 'adlanna'; significati = ''}
else if(parola == 'declinato'){traduzione = 'adlannen'; significati = ''}
else if(parola == 'declinazione'){traduzione = 'adlannad'; significati = ''}
else if(parola == 'del'){traduzione = 'en'; significati = ''}
else if(parola == 'demone'){traduzione = 'raug'; significati = ''}
else if(parola == 'dente'){traduzione = 'nagol'; significati = ''}
else if(parola == 'desiderare'){traduzione = 'anira'; significati = ''}
else if(parola == 'desiderato'){traduzione = 'anirnen'; significati = ''}
else if(parola == 'desiderio'){traduzione = 'anirad'; significati = ''}
else if(parola == 'destinante'){traduzione = 'barthol'; significati = ''}
else if(parola == 'destinare'){traduzione = 'bartha'; significati = ''}
else if(parola == 'destinato'){traduzione = 'barthannen'; significati = ''}
else if(parola == 'destra'){traduzione = 'fair'; significati = ''}
else if(parola == 'detto'){traduzione = 'pennen'; significati = ''}
else if(parola == 'di noi'){traduzione = 'ammen'; significati = ''}
else if(parola == 'di'){traduzione = 'id'; significati = ''}
else if(parola == 'dieci'){traduzione = 'caer'; significati = ''}
else if(parola == 'dietro'){traduzione = 'adel'; significati = ''}
else if(parola == 'difendere'){traduzione = 'sharel'; significati = ''}
else if(parola == 'difesa'){traduzione = 'shar'; significati = ''}
else if(parola == 'diffidare'){traduzione = 'ruckat'; significati = ''}
else if(parola == 'dio'){traduzione = 'khi'; significati = ''}
else if(parola == 'dipartire'){traduzione = 'gwanna'; significati = ''}
else if(parola == 'dipartita'){traduzione = 'gwannad'; significati = ''}
else if(parola == 'dipartito'){traduzione = 'gwannen'; significati = ''}
else if(parola == 'dire'){traduzione = 'ped'; significati = ''}
else if(parola == 'discepolo'){traduzione = 'aphadon'; significati = ''}
else if(parola == 'discorso'){traduzione = 'peded'; significati = ''}
else if(parola == 'discussione'){traduzione = 'athrabeth'; significati = ''}
else if(parola == 'dito'){traduzione = 'lebed'; significati = ''}
else if(parola == 'diurno'){traduzione = 'arad'; significati = ''}
else if(parola == 'divieto'){traduzione = 'bodad'; significati = ''}
else if(parola == 'dolore'){traduzione = 'nir'; significati = ''}
else if(parola == 'dolore'){traduzione = 'prect'; significati = ''}
else if(parola == 'domani'){traduzione = 'viskor'; significati = ''}
else if(parola == 'dondolante'){traduzione = 'glingol'; significati = ''}
else if(parola == 'donna'){traduzione = 'bess'; significati = ''}
else if(parola == 'donna'){traduzione = 'elannah'; significati = ''}
else if(parola == 'dono'){traduzione = 'annad'; significati = ''}
else if(parola == 'dopo'){traduzione = 'ab'; significati = ''}
else if(parola == 'doppio'){traduzione = 'adu'; significati = ''}
else if(parola == 'dormire'){traduzione = 'fecwed'; significati = ''}
else if(parola == 'dovere'){traduzione = 'verokh'; significati = ''}
else if(parola == 'drago'){traduzione = 'lhug'; significati = ''}
else if(parola == 'drago'){traduzione = 'rahkoon'; significati = ''}
else if(parola == 'drenaggio'){traduzione = 'sauthad'; significati = ''}
else if(parola == 'drenante'){traduzione = 'sauthol'; significati = ''}
else if(parola == 'drenare'){traduzione = 'sautha'; significati = ''}
else if(parola == 'drenato'){traduzione = 'sauthannen'; significati = ''}
else if(parola == 'dritto'){traduzione = 'taer'; significati = ''}
else if(parola == 'druido'){traduzione = 'raisham'; significati = ''}
else if(parola == 'due'){traduzione = 'tad'; significati = ''}
else if(parola == 'e'){traduzione = 'ar'; significati = ''}
else if(parola == 'echeggiante'){traduzione = 'lomen'; significati = ''}
else if(parola == 'eco'){traduzione = 'lom'; significati = ''}
else if(parola == 'edificio'){traduzione = 'quonenterk'; significati = ''}
else if(parola == 'egli'){traduzione = 'e'; significati = ''}
else if(parola == 'egli'){traduzione = 'kle'; significati = ''}
else if(parola == 'elefante'){traduzione = 'annabon'; significati = ''}
else if(parola == 'elevato'){traduzione = 'brand'; significati = ''}
 else if(parola == 'elevazione'){traduzione = 'eriad'; significati = ''}
else if(parola == 'elfo'){traduzione = 'edhel'; significati = ''}
else if(parola == 'elfo'){traduzione = 'runah'; significati = ''}
else if(parola == 'elmo'){traduzione = 'thol'; significati = ''}
else if(parola == 'entrante'){traduzione = 'minnol'; significati = ''}
else if(parola == 'entrare'){traduzione = 'minna'; significati = ''}
else if(parola == 'entrata'){traduzione = 'neledhed'; significati = ''}
else if(parola == 'entrato'){traduzione = 'nelennen'; significati = ''}
else if(parola == 'erba'){traduzione = 'salch'; significati = ''}
else if(parola == 'errante'){traduzione = 'raun'; significati = ''}
else if(parola == 'esaminare'){traduzione = 'zanthi'; significati = ''}
else if(parola == 'esile'){traduzione = 'fim'; significati = ''}
else if(parola == 'esiliato'){traduzione = 'edledhir'; significati = ''}
else if(parola == 'essere'){traduzione = 'cuina'; significati = ''}
else if(parola == 'essere'){traduzione = 'erut'; significati = ''}
else if(parola == 'essi'){traduzione = 'siue'; significati = ''}
else if(parola == 'est'){traduzione = 'rhun'; significati = ''}
else if(parola == 'evadere'){traduzione = 'breitha'; significati = ''}
else if(parola == 'evasione'){traduzione = 'breithad'; significati = ''}
else if(parola == 'evaso'){traduzione = 'breithannen'; significati = ''}
else if(parola == 'faccia'){traduzione = 'nif'; significati = ''}
else if(parola == 'facente'){traduzione = 'carel'; significati = ''}
else if(parola == 'faggio'){traduzione = 'fer'; significati = ''}
else if(parola == 'fare'){traduzione = 'car'; significati = ''}
else if(parola == 'fare'){traduzione = 'opakh'; significati = ''}
else if(parola == 'farfalla'){traduzione = 'gwilwileth'; significati = ''}
else if(parola == 'fatto'){traduzione = 'coren'; significati = ''}
else if(parola == 'fattore'){traduzione = 'nandor'; significati = ''}
else if(parola == 'fauci'){traduzione = 'anca'; significati = ''}
else if(parola == 'favore'){traduzione = 'helcomh'; significati = ''}
else if(parola == 'femminile'){traduzione = 'belask'; significati = ''}
else if(parola == 'fendente'){traduzione = 'dravol'; significati = ''}
else if(parola == 'fendere'){traduzione = 'rista'; significati = ''}
else if(parola == 'fenditura'){traduzione = 'criss'; significati = ''}
else if(parola == 'ferire'){traduzione = 'harna'; significati = ''}
else if(parola == 'ferita'){traduzione = 'haru'; significati = ''}
else if(parola == 'ferito'){traduzione = 'harnannen'; significati = ''}
else if(parola == 'fermare'){traduzione = 'dar'; significati = ''}
else if(parola == 'fermata'){traduzione = 'dared'; significati = ''}
else if(parola == 'fermato'){traduzione = 'darnen'; significati = ''}
else if(parola == 'festa'){traduzione = 'mereth'; significati = ''}
else if(parola == 'fiamma'){traduzione = 'lach'; significati = ''}
else if(parola == 'fiamme'){traduzione = 'wesn'; significati = ''}
else if(parola == 'figlia'){traduzione = 'sell'; significati = ''}
else if(parola == 'figlio'){traduzione = 'ion'; significati = ''}
else if(parola == 'figura'){traduzione = 'cant'; significati = ''}
else if(parola == 'fila'){traduzione = 'lir'; significati = ''}
else if(parola == 'fine'){traduzione = 'meth'; significati = ''}
else if(parola == 'finestra'){traduzione = 'henneth'; significati = ''}
else if(parola == 'fino'){traduzione = 'carin'; significati = ''}
else if(parola == 'fionda'){traduzione = 'taidah'; significati = ''}
else if(parola == 'fiore'){traduzione = 'loth'; significati = ''}
else if(parola == 'fioritura'){traduzione = 'gwaloth'; significati = ''}
else if(parola == 'fisare'){traduzione = 'penia'; significati = ''}
else if(parola == 'fissante'){traduzione = 'peniol'; significati = ''}
else if(parola == 'fissato'){traduzione = 'peniannen'; significati = ''}
else if(parola == 'fiume'){traduzione = 'amx'; significati = ''}
else if(parola == 'fiume'){traduzione = 'duin'; significati = ''}
else if(parola == 'foglia'){traduzione = 'lass'; significati = ''}
else if(parola == 'fondo'){traduzione = 'soongh'; significati = ''}
else if(parola == 'fontana'){traduzione = 'celu'; significati = ''}
else if(parola == 'fonte'){traduzione = 'eithel'; significati = ''}
else if(parola == 'forte'){traduzione = 'bell'; significati = ''}
else if(parola == 'fortezza'){traduzione = 'ost'; significati = ''}
else if(parola == 'fortuna'){traduzione = 'milek'; significati = ''}
else if(parola == 'fortunato'){traduzione = 'milekor'; significati = ''}
else if(parola == 'fratello'){traduzione = 'hantis'; significati = ''}
else if(parola == 'fratello'){traduzione = 'tor'; significati = ''}
else if(parola == 'freccia'){traduzione = 'rane'; significati = ''}
else if(parola == 'freddo'){traduzione = 'him'; significati = ''}
else if(parola == 'fremente'){traduzione = 'girel'; significati = ''}
else if(parola == 'fremere'){traduzione = 'gir'; significati = ''}
else if(parola == 'fremito'){traduzione = 'gired'; significati = ''}
else if(parola == 'frequente'){traduzione = 'remb'; significati = ''}
else if(parola == 'fresco'){traduzione = 'laeb'; significati = ''}
else if(parola == 'frutta'){traduzione = 'diler'; significati = ''}
else if(parola == 'fuga'){traduzione = 'dregad'; significati = ''}
else if(parola == 'fuggente'){traduzione = 'dregol'; significati = ''}
else if(parola == 'fuggiasco'){traduzione = 'dregir'; significati = ''}
else if(parola == 'fuggire'){traduzione = 'dreg'; significati = ''}
else if(parola == 'fuggito'){traduzione = 'dregannen'; significati = ''}
else if(parola == 'fulminare'){traduzione = 'kewozak'; significati = ''}
else if(parola == 'fulmine'){traduzione = 'kewo'; significati = ''}
else if(parola == 'fuoco'){traduzione = 'forah'; significati = ''}
else if(parola == 'fuoco'){traduzione = 'naur'; significati = ''}
else if(parola == 'fuori'){traduzione = 'ed'; significati = ''}
else if(parola == 'furbo'){traduzione = 'dukat'; significati = ''}
else if(parola == 'gabbiano'){traduzione = 'maew'; significati = ''}
else if(parola == 'galleggiamento'){traduzione = 'lodad'; significati = ''}
else if(parola == 'galleggiante'){traduzione = 'lodol'; significati = ''}
else if(parola == 'galleggiare'){traduzione = 'loda'; significati = ''}
else if(parola == 'galleggiato'){traduzione = 'lunnen'; significati = ''}
else if(parola == 'gallina'){traduzione = 'sliut'; significati = ''}
else if(parola == 'gallo'){traduzione = 'smaesh'; significati = ''}
else if(parola == 'gamba'){traduzione = 'homhod'; significati = ''}
else if(parola == 'gambo'){traduzione = 'telch'; significati = ''}
else if(parola == 'gatto'){traduzione = 'iftz'; significati = ''}
else if(parola == 'gelante'){traduzione = 'helel'; significati = ''}
else if(parola == 'gelare'){traduzione = 'hel'; significati = ''}
else if(parola == 'gelata'){traduzione = 'heled'; significati = ''}
else if(parola == 'gelato'){traduzione = 'hellen'; significati = ''}
else if(parola == 'gelo'){traduzione = 'heloth'; significati = ''}
else if(parola == 'gemelli'){traduzione = 'gwanum'; significati = ''}
else if(parola == 'gemelli'){traduzione = 'gwanun'; significati = ''}
else if(parola == 'gemello'){traduzione = 'gwanuning'; significati = ''}
else if(parola == 'generare'){traduzione = 'onna'; significati = ''}
else if(parola == 'generato'){traduzione = 'onnen'; significati = ''}
else if(parola == 'generatore'){traduzione = 'edonnir'; significati = ''}
else if(parola == 'generazione'){traduzione = 'onnad'; significati = ''}
else if(parola == 'gente'){traduzione = 'rim'; significati = ''}
else if(parola == 'ghiaccio'){traduzione = 'heleg'; significati = ''}
else if(parola == 'ghiaccio'){traduzione = 'vorash'; significati = ''}
else if(parola == 'ghiaia'){traduzione = 'birith'; significati = ''}
else if(parola == 'giallo'){traduzione = 'malen'; significati = ''}
else if(parola == 'ginestrone'){traduzione = 'aeglos'; significati = ''}
else if(parola == 'giocare'){traduzione = 'teilia'; significati = ''}
else if(parola == 'gioco'){traduzione = 'teliad'; significati = ''}
else if(parola == 'gioiello'){traduzione = 'mir'; significati = ''}
else if(parola == 'giovane'){traduzione = 'neth'; significati = ''}
else if(parola == 'girare'){traduzione = 'hwinia'; significati = ''}
else if(parola == 'girato'){traduzione = 'hwiniannen'; significati = ''}
else if(parola == 'giro'){traduzione = 'hwiniad'; significati = ''}
else if(parola == 'giù'){traduzione = 'dad'; significati = ''}
else if(parola == 'giù'){traduzione = 'kor'; significati = ''}
else if(parola == 'giudice'){traduzione = 'badhor'; significati = ''}
else if(parola == 'giuramento'){traduzione = 'gwestad'; significati = ''}
else if(parola == 'giurare'){traduzione = 'gwesta'; significati = ''}
else if(parola == 'giurato'){traduzione = 'gwestannen'; significati = ''}
else if(parola == 'gli elfi'){traduzione = 'eledhrim'; significati = ''}
else if(parola == 'gli hobbit'){traduzione = 'periannath'; significati = ''}
else if(parola == 'gli orchi'){traduzione = 'orchoth'; significati = ''}
else if(parola == 'gli'){traduzione = 'fli'; significati = ''}
else if(parola == 'gloria'){traduzione = 'aglar'; significati = ''}
else if(parola == 'glorificare'){traduzione = 'egleria'; significati = ''}
else if(parola == 'glorificato'){traduzione = 'egleriannen'; significati = ''}
else if(parola == 'glorioso'){traduzione = 'aglareb'; significati = ''}
else if(parola == 'gnomo'){traduzione = 'kazur'; significati = ''}
else if(parola == 'gonfiamento'){traduzione = 'tuiad'; significati = ''}
else if(parola == 'gonfiante'){traduzione = 'tuiol'; significati = ''}
else if(parola == 'gonfiarsi'){traduzione = 'tuia'; significati = ''}
else if(parola == 'gonfiato'){traduzione = 'tuiannen'; significati = ''}
else if(parola == 'graffiante'){traduzione = 'rhibel'; significati = ''}
else if(parola == 'graffiato'){traduzione = 'rhimmen'; significati = ''}
else if(parola == 'graffio'){traduzione = 'rhibed'; significati = ''}
else if(parola == 'grande'){traduzione = 'roval'; significati = ''}
else if(parola == 'grandine'){traduzione = 'esha'; significati = ''}
else if(parola == 'grigio'){traduzione = 'thind'; significati = ''}
else if(parola == 'grotta'){traduzione = 'rond'; significati = ''}
else if(parola == 'guado'){traduzione = 'athr'; significati = ''}
else if(parola == 'guancia'){traduzione = 'fads'; significati = ''}
else if(parola == 'guardare'){traduzione = 'tir'; significati = ''}
else if(parola == 'guardato'){traduzione = 'tirannen'; significati = ''}
else if(parola == 'guardia'){traduzione = 'vortah'; significati = ''}
else if(parola == 'guardiano'){traduzione = 'tirdir'; significati = ''}
else if(parola == 'guarigione'){traduzione = 'nestad'; significati = ''}
else if(parola == 'guarire'){traduzione = 'nesta'; significati = ''}
else if(parola == 'guarito'){traduzione = 'nestannen'; significati = ''}
else if(parola == 'guerra'){traduzione = 'tamak'; significati = ''}
else if(parola == 'guerriero'){traduzione = 'vorth'; significati = ''}
else if(parola == 'halfling'){traduzione = 'hullian'; significati = ''}
else if(parola == 'i'){traduzione = 'fli'; significati = ''}
else if(parola == 'idea'){traduzione = 'nau'; significati = ''}
else if(parola == 'ieri'){traduzione = 'tasker'; significati = ''}
else if(parola == 'il'){traduzione = 'i (oppure slo)'; significati = ''}
else if(parola == 'immortale'){traduzione = 'alfirin'; significati = ''}
else if(parola == 'impasto'){traduzione = 'moeas'; significati = ''}
else if(parola == 'impiccato'){traduzione = 'glingir'; significati = ''}
else if(parola == 'impigliare'){traduzione = 'gonathra'; significati = ''}
else if(parola == 'impiglio'){traduzione = 'gonathrad'; significati = ''}
else if(parola == 'improvviso'){traduzione = 'bragol'; significati = ''}
else if(parola == 'in'){traduzione = 'ned (oppure ni)'; significati = ''}
else if(parola == 'incantamento'){traduzione = 'luthad'; significati = ''}
else if(parola == 'incantare'){traduzione = 'lutha'; significati = ''}
else if(parola == 'incantato'){traduzione = 'luthannen'; significati = ''}
else if(parola == 'incantatrice'){traduzione = 'luthien'; significati = ''}
else if(parola == 'incantesimo'){traduzione = 'luth'; significati = ''}
else if(parola == 'incendiare'){traduzione = 'wesnen'; significati = ''} 
else if(parola == 'incendio'){traduzione = 'kunst'; significati = ''}
else if(parola == 'incenerire'){traduzione = 'kunsternerk'; significati = ''} 
else if(parola == 'inclinato'){traduzione = 'adlann'; significati = ''}
else if(parola == 'incontare'){traduzione = 'govad'; significati = ''}
else if(parola == 'incontrante'){traduzione = 'govadel'; significati = ''}
else if(parola == 'incontrato'){traduzione = 'govannen'; significati = ''}
else if(parola == 'incontro'){traduzione = 'govaded'; significati = ''}
else if(parola == 'ingarbugliare'){traduzione = 'gonathra'; significati = ''}
else if(parola == 'iniziare'){traduzione = 'heria'; significati = ''}
else if(parola == 'iniziato'){traduzione = 'heriannen'; significati = ''}
else if(parola == 'inizio'){traduzione = 'heriad'; significati = ''}
else if(parola == 'inno'){traduzione = 'aerlinn'; significati = ''}
else if(parola == 'inseguire'){traduzione = 'fillon'; significati = ''}
else if(parola == 'inserimento'){traduzione = 'nestaged'; significati = ''}
else if(parola == 'inserire'){traduzione = 'nestag'; significati = ''}
else if(parola == 'inserito'){traduzione = 'nestangen'; significati = ''}
else if(parola == 'insieme'){traduzione = 'go'; significati = ''}
else if(parola == 'insultare'){traduzione = 'eitha'; significati = ''}
else if(parola == 'insulto'){traduzione = 'eithad'; significati = ''}
else if(parola == 'intelligente'){traduzione = 'hand'; significati = ''}
else if(parola == 'intenzione'){traduzione = 'theled'; significati = ''}
else if(parola == 'inumidimento'){traduzione = 'limmidad'; significati = ''}
else if(parola == 'inumidire'){traduzione = 'limmida'; significati = ''}
else if(parola == 'inumidito'){traduzione = 'limminnen'; significati = ''}
else if(parola == 'inverno'){traduzione = 'rhiw'; significati = ''}
else if(parola == 'invocante'){traduzione = 'nallolo'; significati = ''}
else if(parola == 'invocare'){traduzione = 'nalla'; significati = ''}
else if(parola == 'invocato'){traduzione = 'nallannen'; significati = ''}
else if(parola == 'invocazione'){traduzione = 'nallad'; significati = ''}
else if(parola == 'io'){traduzione = 'hoi'; significati = ''}
else if(parola == 'io'){traduzione = 'im'; significati = ''}
else if(parola == 'isola'){traduzione = 'toll'; significati = ''}
else if(parola == 'la'){traduzione = 'i (oppure slo)'; significati = ''}
else if(parola == 'là'){traduzione = 'olò'; significati = ''}
else if(parola == 'lacerazione'){traduzione = 'ristad'; significati = ''}
else if(parola == 'ladro'){traduzione = 'karilh'; significati = ''}
else if(parola == 'laggiù'){traduzione = 'seld'; significati = ''}
else if(parola == 'laghetto'){traduzione = 'ael'; significati = ''}
else if(parola == 'lama'){traduzione = 'hathel'; significati = ''}
else if(parola == 'lamento'){traduzione = 'ninios'; significati = ''}
else if(parola == 'lampo'){traduzione = 'grwun'; significati = ''}
else if(parola == 'lana'){traduzione = 'taw'; significati = ''}
else if(parola == 'lancia'){traduzione = 'ech'; significati = ''}
else if(parola == 'lanciante'){traduzione = 'hadel'; significati = ''}
else if(parola == 'lanciare'){traduzione = 'rib'; significati = ''}
else if(parola == 'lanciato'){traduzione = 'hannen'; significati = ''}
else if(parola == 'lanciatore'){traduzione = 'hador'; significati = ''}
else if(parola == 'lancio'){traduzione = 'haded'; significati = ''}
else if(parola == 'languore'){traduzione = 'firith'; significati = ''}
else if(parola == 'lassù'){traduzione = 'sond'; significati = ''}
else if(parola == 'lavorare'){traduzione = 'muda'; significati = ''}
else if(parola == 'lavoratore'){traduzione = 'mudadir'; significati = ''}
else if(parola == 'le'){traduzione = 'fli'; significati = ''}
else if(parola == 'leccaggio'){traduzione = 'laved'; significati = ''}
else if(parola == 'leccante'){traduzione = 'lavel'; significati = ''}
else if(parola == 'leccare'){traduzione = 'lav'; significati = ''}
else if(parola == 'leccato'){traduzione = 'lammen'; significati = ''}
else if(parola == 'legante'){traduzione = 'nodel'; significati = ''}
else if(parola == 'legare'){traduzione = 'gwedh'; significati = ''}
else if(parola == 'legato'){traduzione = 'gwedhannen'; significati = ''}
else if(parola == 'lei'){traduzione = 'iuel'; significati = ''}
else if(parola == 'leone'){traduzione = 'raw'; significati = ''}
else if(parola == 'lettera'){traduzione = 'tew'; significati = ''}
else if(parola == 'letto'){traduzione = 'haust'; significati = ''}
else if(parola == 'lì'){traduzione = 'ol'; significati = ''}
else if(parola == 'liberatore'){traduzione = 'leithir'; significati = ''}
else if(parola == 'libero'){traduzione = 'lain'; significati = ''}
else if(parola == 'lingua'){traduzione = 'lam'; significati = ''}
else if(parola == 'lisciare'){traduzione = 'lada'; significati = ''}
else if(parola == 'lite'){traduzione = 'cost'; significati = ''}
else if(parola == 'lo'){traduzione = 'i'; significati = ''}
else if(parola == 'lo'){traduzione = 'slo'; significati = ''}
else if(parola == 'locanda'){traduzione = 'kuffy'; significati = ''}
else if(parola == 'lontano'){traduzione = 'palan'; significati = ''}
else if(parola == 'loro'){traduzione = 'hain'; significati = ''}
else if(parola == 'loro'){traduzione = 'orol'; significati = ''}
else if(parola == 'luce'){traduzione = 'calad'; significati = ''}
else if(parola == 'luce'){traduzione = 'laxeh'; significati = ''}
else if(parola == 'lucentezza'){traduzione = 'ril'; significati = ''}
else if(parola == 'luglio'){traduzione = 'cerveth'; significati = ''}
else if(parola == 'lui'){traduzione = 'iuel'; significati = ''}
else if(parola == 'luminosità'){traduzione = 'thil'; significati = ''}
else if(parola == 'luna'){traduzione = 'ithil'; significati = ''}
else if(parola == 'luna'){traduzione = 'ran'; significati = ''}
else if(parola == 'luna'){traduzione = 'rovh'; significati = ''}
else if(parola == 'lungo'){traduzione = 'and'; significati = ''}
else if(parola == 'lupo'){traduzione = 'draug'; significati = ''}
else if(parola == 'lussurioso'){traduzione = 'maelui'; significati = ''}
else if(parola == 'lutto'){traduzione = 'nienor'; significati = ''}
else if(parola == 'madre'){traduzione = 'hatha'; significati = ''}
else if(parola == 'madre'){traduzione = 'naneth'; significati = ''}
else if(parola == 'maestà'){traduzione = 'mekoth'; significati = ''}
else if(parola == 'maestro'){traduzione = 'herdir'; significati = ''}
else if(parola == 'maggio'){traduzione = 'lothron'; significati = ''}
else if(parola == 'magia'){traduzione = 'brien'; significati = ''}
else if(parola == 'magia'){traduzione = 'gul'; significati = ''}
else if(parola == 'maglia'){traduzione = 'rem'; significati = ''}
else if(parola == 'mago'){traduzione = 'curunir'; significati = ''}
else if(parola == 'mago'){traduzione = 'rakolh'; significati = ''}
else if(parola == 'magro'){traduzione = 'ihain'; significati = ''}
else if(parola == 'malato'){traduzione = 'ihaew'; significati = ''}
else if(parola == 'malattia'){traduzione = 'ihiw'; significati = ''}
else if(parola == 'male'){traduzione = 'ury'; significati = ''}
else if(parola == 'malediozione'){traduzione = 'uryunagako'; significati = ''}
else if(parola == 'maledire'){traduzione = 'uryus'; significati = ''}
else if(parola == 'maledizione'){traduzione = 'rhach'; significati = ''}
else if(parola == 'maneggiante'){traduzione = 'torthol'; significati = ''}
else if(parola == 'maneggiare'){traduzione = 'tortha'; significati = ''}
else if(parola == 'maneggiato'){traduzione = 'mathannen'; significati = ''}
else if(parola == 'maneggio'){traduzione = 'torthad'; significati = ''}
else if(parola == 'mangiare'){traduzione = 'dipatsek'; significati = ''}
else if(parola == 'mangiare'){traduzione = 'mad'; significati = ''}
else if(parola == 'mangiato'){traduzione = 'mannen'; significati = ''}
else if(parola == 'mano'){traduzione = 'cam'; significati = ''}
else if(parola == 'mano'){traduzione = 'kiokk'; significati = ''}
else if(parola == 'marcio'){traduzione = 'frizi'; significati = ''}
else if(parola == 'marcire'){traduzione = 'friziaan'; significati = ''}
else if(parola == 'mare'){traduzione = 'gae'; significati = ''}
else if(parola == 'mare'){traduzione = 'hoyot'; significati = ''}
else if(parola == 'marito'){traduzione = 'herven'; significati = ''}
else if(parola == 'marrone'){traduzione = 'rhosch'; significati = ''}
else if(parola == 'martellante'){traduzione = 'dammol'; significati = ''}
else if(parola == 'martellare'){traduzione = 'damma'; significati = ''}
else if(parola == 'martellato'){traduzione = 'damminen'; significati = ''}
else if(parola == 'martello'){traduzione = 'dam'; significati = ''}
else if(parola == 'marzo'){traduzione = 'gwaeron'; significati = ''}
else if(parola == 'maschile'){traduzione = 'baskor'; significati = ''}
else if(parola == 'mazza'){traduzione = 'grond'; significati = ''}
else if(parola == 'mazza'){traduzione = 'klaah'; significati = ''}
else if(parola == 'me'){traduzione = 'em'; significati = ''}
else if(parola == 'meglio'){traduzione = 'wond'; significati = ''}
else if(parola == 'melodioso'){traduzione = 'lend'; significati = ''}
else if(parola == 'meridionale'){traduzione = 'harnen'; significati = ''}
else if(parola == 'meschino'){traduzione = 'niben'; significati = ''}
else if(parola == 'metallo'){traduzione = 'raud'; significati = ''}
else if(parola == 'mezzelfo'){traduzione = 'denerunha'; significati = ''}
else if(parola == 'mezzelfo'){traduzione = 'peredhel'; significati = ''}
else if(parola == 'mezzo'){traduzione = 'dener'; significati = ''}
else if(parola == 'mezzouomo'){traduzione = 'perian'; significati = ''}
else if(parola == 'miele'){traduzione = 'gli'; significati = ''}
else if(parola == 'mietere'){traduzione = 'critha'; significati = ''}
else if(parola == 'mietitore'){traduzione = 'crithir'; significati = ''}
else if(parola == 'mietitura'){traduzione = 'crithad'; significati = ''}
else if(parola == 'mietuto'){traduzione = 'crithannen'; significati = ''}
else if(parola == 'migliore'){traduzione = 'wonder'; significati = ''}
else if(parola == 'minuscolo'){traduzione = 'tithen'; significati = ''}
else if(parola == 'mio'){traduzione = 'nin'; significati = ''}
else if(parola == 'miseria'){traduzione = 'kanazza'; significati = ''}
else if(parola == 'moglie'){traduzione = 'herves'; significati = ''}
else if(parola == 'molle'){traduzione = 'moe'; significati = ''}
else if(parola == 'montagna'){traduzione = 'orod'; significati = ''}
else if(parola == 'montanaro'){traduzione = 'orodben'; significati = ''}
else if(parola == 'mordere'){traduzione = 'nag'; significati = ''}
else if(parola == 'morire'){traduzione = 'vortham'; significati = ''}
else if(parola == 'morso'){traduzione = 'naged'; significati = ''}
else if(parola == 'mortale'){traduzione = 'fireb'; significati = ''}
else if(parola == 'mortali'){traduzione = 'firiath'; significati = ''}
else if(parola == 'morte'){traduzione = 'gurth'; significati = ''}
else if(parola == 'morte'){traduzione = 'vortha'; significati = ''}
else if(parola == 'morto'){traduzione = 'fern'; significati = ''}
else if(parola == 'mostro'){traduzione = 'ulun'; significati = ''}
else if(parola == 'mostruoso'){traduzione = 'uanui'; significati = ''}
else if(parola == 'mucca'){traduzione = 'feunc'; significati = ''}
else if(parola == 'muro'){traduzione = 'ram'; significati = ''}
else if(parola == 'musica'){traduzione = 'dener'; significati = ''}
else if(parola == 'muso'){traduzione = 'bund'; significati = ''}
else if(parola == 'nani'){traduzione = 'naugrim'; significati = ''}
else if(parola == 'nano'){traduzione = 'bouth'; significati = ''}
else if(parola == 'narratore'){traduzione = 'nardir'; significati = ''}
else if(parola == 'nascondere'){traduzione = 'delia'; significati = ''}
else if(parola == 'nascosto'){traduzione = 'dolen'; significati = ''}
else if(parola == 'naso'){traduzione = 'nem'; significati = ''}
else if(parola == 'nato'){traduzione = 'hodo'; significati = ''}
else if(parola == 'nave'){traduzione = 'cair'; significati = ''}
else if(parola == 'nebbia'){traduzione = 'hithu'; significati = ''}
else if(parola == 'nebbioso'){traduzione = 'hithui'; significati = ''}
else if(parola == 'negazione'){traduzione = 'ubed'; significati = ''}
else if(parola == 'negromanzia'){traduzione = 'morgul'; significati = ''}
else if(parola == 'nel'){traduzione = 'ben'; significati = ''}
else if(parola == 'nel'){traduzione = 'elk'; significati = ''}
else if(parola == 'nemico'){traduzione = 'coth'; significati = ''}
else if(parola == 'nero'){traduzione = 'morn'; significati = ''}
else if(parola == 'neve'){traduzione = 'hitja'; significati = ''}
else if(parola == 'neve'){traduzione = 'loss'; significati = ''}
else if(parola == 'nevicare'){traduzione = 'hitjail'; significati = ''}
else if(parola == 'no'){traduzione = 'baw'; significati = ''}
else if(parola == 'no'){traduzione = 'koh'; significati = ''}
else if(parola == 'nobile'){traduzione = 'nabekoon'; significati = ''}
else if(parola == 'noi'){traduzione = 'oni'; significati = ''}
else if(parola == 'noi'){traduzione = 'oni'; significati = ''}
else if(parola == 'noldo'){traduzione = 'golodh'; significati = ''}
else if(parola == 'nomade'){traduzione = 'amrod'; significati = ''}
else if(parola == 'non'){traduzione = 'avo'; significati = ''}
else if(parola == 'non'){traduzione = 'inx'; significati = ''}
else if(parola == 'nord'){traduzione = 'forod'; significati = ''}
else if(parola == 'notte'){traduzione = 'du'; significati = ''}
else if(parola == 'nove'){traduzione = 'neder'; significati = ''}
else if(parola == 'novembre'){traduzione = 'hithui'; significati = ''}
else if(parola == 'nube'){traduzione = 'lum'; significati = ''}
else if(parola == 'nudo'){traduzione = 'lanc'; significati = ''}
else if(parola == 'nuotare'){traduzione = 'rakerh'; significati = ''}
else if(parola == 'nuovo'){traduzione = 'gwain'; significati = ''}
else if(parola == 'nuovo'){traduzione = 'zaboh'; significati = ''}
else if(parola == 'nuvola'){traduzione = 'faun'; significati = ''}
else if(parola == 'oca'){traduzione = 'gwaun'; significati = ''}
else if(parola == 'occhio'){traduzione = 'hen'; significati = ''}
else if(parola == 'occhio'){traduzione = 'jellarim'; significati = ''}
else if(parola == 'occidentale'){traduzione = 'annui'; significati = ''}
else if(parola == 'occultamento'){traduzione = 'deliad'; significati = ''}
else if(parola == 'oden'){traduzione = 'odin'; significati = ''}
else if(parola == 'odio'){traduzione = 'glam'; significati = ''}
else if(parola == 'odioso'){traduzione = 'glamog'; significati = ''}
else if(parola == 'oggi'){traduzione = 'laskar'; significati = ''}
else if(parola == 'olmo'){traduzione = 'lalf'; significati = ''}
else if(parola == 'oltre'){traduzione = 'athan'; significati = ''}
else if(parola == 'ombra'){traduzione = 'dae'; significati = ''}
else if(parola == 'ombra'){traduzione = 'kamok'; significati = ''}
else if(parola == 'ombroso'){traduzione = 'gwathren'; significati = ''}
else if(parola == 'oppressione'){traduzione = 'bauglad'; significati = ''}
else if(parola == 'oppresso'){traduzione = 'bauglannen'; significati = ''}
else if(parola == 'opprimente'){traduzione = 'bauglol'; significati = ''}
else if(parola == 'opprimere'){traduzione = 'baugla'; significati = ''}
else if(parola == 'orafo'){traduzione = 'mirdan'; significati = ''}
else if(parola == 'oratore'){traduzione = 'pedir'; significati = ''}
else if(parola == 'orco'){traduzione = 'orch'; significati = ''}
else if(parola == 'orda'){traduzione = 'hoth'; significati = ''}
else if(parola == 'ordine'){traduzione = 'heren'; significati = ''}
else if(parola == 'orecchie'){traduzione = 'ihaw'; significati = ''}
else if(parola == 'orecchie'){traduzione = 'lhaw'; significati = ''}
else if(parola == 'orecchio'){traduzione = 'hotoquosh'; significati = ''}
else if(parola == 'orecchio'){traduzione = 'lhewig'; significati = ''}
else if(parola == 'orientale'){traduzione = 'rhunen'; significati = ''}
else if(parola == 'origliante'){traduzione = 'lathr'; significati = ''}
else if(parola == 'origliare'){traduzione = 'lathr'; significati = ''}
else if(parola == 'origliato'){traduzione = 'lathrannen'; significati = ''}
else if(parola == 'orione'){traduzione = 'menelvagor'; significati = ''}
else if(parola == 'orlo'){traduzione = 'riw'; significati = ''}
else if(parola == 'oro'){traduzione = 'malt'; significati = ''}
else if(parola == 'orribile'){traduzione = 'gortheb'; significati = ''}
else if(parola == 'orrore'){traduzione = 'del'; significati = ''}
else if(parola == 'orso'){traduzione = 'brog'; significati = ''}
else if(parola == 'osare'){traduzione = 'bertha'; significati = ''}
else if(parola == 'osato'){traduzione = 'berthannen'; significati = ''}
else if(parola == 'oscurità'){traduzione = 'daw'; significati = ''}
else if(parola == 'oscuro'){traduzione = 'dùr'; significati = ''}
else if(parola == 'ostruire'){traduzione = 'dilia'; significati = ''}
else if(parola == 'ostruito'){traduzione = 'diliannen'; significati = ''}
else if(parola == 'ostruzione'){traduzione = 'diliad'; significati = ''}
else if(parola == 'ottenere'){traduzione = 'acheve'; significati = ''}
else if(parola == 'otto'){traduzione = 'toloth'; significati = ''}
else if(parola == 'ottobre'){traduzione = 'narbeleth'; significati = ''}
else if(parola == 'ovest'){traduzione = 'dùn'; significati = ''}
else if(parola == 'pace'){traduzione = 'gwil'; significati = ''}
else if(parola == 'pace'){traduzione = 'gwil'; significati = ''}
else if(parola == 'pace'){traduzione = 'karat'; significati = ''}
else if(parola == 'padre'){traduzione = 'adar'; significati = ''}
else if(parola == 'padre'){traduzione = 'adar'; significati = ''}
else if(parola == 'padre'){traduzione = 'noah'; significati = ''}
else if(parola == 'padrone'){traduzione = 'herdir'; significati = ''}
else if(parola == 'padrone'){traduzione = 'herdir'; significati = ''}
else if(parola == 'pagnotta'){traduzione = 'basgorn'; significati = ''}
else if(parola == 'pagnotta'){traduzione = 'basgorn'; significati = ''}
else if(parola == 'paladino'){traduzione = 'kollyor'; significati = ''}
else if(parola == 'palazzo'){traduzione = 'quomicos'; significati = ''}
else if(parola == 'pallido'){traduzione = 'malu'; significati = ''}
else if(parola == 'pallido'){traduzione = 'malu'; significati = ''}
else if(parola == 'pallore'){traduzione = 'niphred'; significati = ''}
else if(parola == 'pallore'){traduzione = 'niphred'; significati = ''}
else if(parola == 'palmo'){traduzione = 'camlann'; significati = ''}
else if(parola == 'palmo'){traduzione = 'camlann'; significati = ''}
else if(parola == 'palo'){traduzione = 'ceber'; significati = ''}
else if(parola == 'palo'){traduzione = 'cener'; significati = ''}
else if(parola == 'pan di via'){traduzione = 'lembas'; significati = ''}
else if(parola == 'pane'){traduzione = 'bast'; significati = ''}
else if(parola == 'pane'){traduzione = 'bast'; significati = ''}
else if(parola == 'parola'){traduzione = 'peth'; significati = ''}
else if(parola == 'parola'){traduzione = 'peth'; significati = ''}
else if(parola == 'pascolo'){traduzione = 'nadhor'; significati = ''}
else if(parola == 'pascolo'){traduzione = 'nadhor'; significati = ''}
else if(parola == 'passaggio'){traduzione = 'pendrath'; significati = ''}
else if(parola == 'passo'){traduzione = 'cirith'; significati = ''}
else if(parola == 'passo'){traduzione = 'cirith'; significati = ''}
else if(parola == 'paura'){traduzione = 'gaer'; significati = ''}
else if(parola == 'paura'){traduzione = 'gost'; significati = ''}
else if(parola == 'pavimento'){traduzione = 'panas'; significati = ''}
else if(parola == 'pavimento'){traduzione = 'panas'; significati = ''}
else if(parola == 'pelle'){traduzione = 'daimon'; significati = ''}
else if(parola == 'pendente'){traduzione = 'pendol'; significati = ''}
else if(parola == 'pendente'){traduzione = 'pennol'; significati = ''}
else if(parola == 'pendenza'){traduzione = 'pennad'; significati = ''}
else if(parola == 'pendenza'){traduzione = 'pennad'; significati = ''}
else if(parola == 'pendere'){traduzione = 'penna'; significati = ''}
else if(parola == 'pendio'){traduzione = 'talad'; significati = ''}
else if(parola == 'pendio'){traduzione = 'talad'; significati = ''}
else if(parola == 'penna'){traduzione = 'tegol'; significati = ''}
else if(parola == 'penna'){traduzione = 'tegol'; significati = ''}
else if(parola == 'pensiero'){traduzione = 'ind'; significati = ''}
else if(parola == 'pensosità'){traduzione = 'idhor'; significati = ''}
else if(parola == 'per me stesso'){traduzione = 'anim'; significati = ''}
else if(parola == 'per noi'){traduzione = 'ammen'; significati = ''}
else if(parola == 'per'){traduzione = 'an'; significati = ''}
else if(parola == 'per'){traduzione = 'an'; significati = ''}
else if(parola == 'per'){traduzione = 'orf'; significati = ''}
else if(parola == 'pesante'){traduzione = 'long'; significati = ''}
else if(parola == 'pesante'){traduzione = 'long'; significati = ''}
else if(parola == 'pescare'){traduzione = 'oskter'; significati = ''}
else if(parola == 'pesce'){traduzione = 'lim'; significati = ''}
else if(parola == 'pesce'){traduzione = 'lim'; significati = ''}
else if(parola == 'pesce'){traduzione = 'osk'; significati = ''}
else if(parola == 'piana'){traduzione = 'lad'; significati = ''}
else if(parola == 'piana'){traduzione = 'lad'; significati = ''}
else if(parola == 'piangente'){traduzione = 'ninnol'; significati = ''}
else if(parola == 'piangente'){traduzione = 'ninnol'; significati = ''}
else if(parola == 'piangere'){traduzione = 'marded'; significati = ''}
else if(parola == 'piangere'){traduzione = 'ninna'; significati = ''}
else if(parola == 'piangere'){traduzione = 'ninna'; significati = ''}
else if(parola == 'pianta'){traduzione = 'tellain'; significati = ''}
else if(parola == 'pianto'){traduzione = 'ninned'; significati = ''}
else if(parola == 'pianto'){traduzione = 'ninnen'; significati = ''}
else if(parola == 'pianura'){traduzione = 'talath'; significati = ''}
else if(parola == 'pianura'){traduzione = 'talath'; significati = ''}
else if(parola == 'piattaforma'){traduzione = 'talan'; significati = ''}
else if(parola == 'piattaforma'){traduzione = 'talan'; significati = ''}
else if(parola == 'piatto'){traduzione = 'talu'; significati = ''}
else if(parola == 'piatto'){traduzione = 'talu'; significati = ''}
else if(parola == 'picchio'){traduzione = 'tavor'; significati = ''}
else if(parola == 'picchio'){traduzione = 'tavor'; significati = ''}
else if(parola == 'picco'){traduzione = 'aegas'; significati = ''}
else if(parola == 'piede'){traduzione = 'sturmazag'; significati = ''}
else if(parola == 'piede'){traduzione = 'tal'; significati = ''}
else if(parola == 'piede'){traduzione = 'tal'; significati = ''}
else if(parola == 'pieno'){traduzione = 'pant'; significati = ''}
else if(parola == 'pieno'){traduzione = 'pant'; significati = ''}
else if(parola == 'pietra'){traduzione = 'sarn'; significati = ''}
else if(parola == 'pietra'){traduzione = 'sarn'; significati = ''}
else if(parola == 'pino'){traduzione = 'thon'; significati = ''}
else if(parola == 'pino'){traduzione = 'thon'; significati = ''}
else if(parola == 'pioggia'){traduzione = 'eliad'; significati = ''}
else if(parola == 'pioggia'){traduzione = 'eliad'; significati = ''}
else if(parola == 'pioggia'){traduzione = 'shaza'; significati = ''}
else if(parola == 'pioppo'){traduzione = 'tulus'; significati = ''}
else if(parola == 'pioppo'){traduzione = 'tulus'; significati = ''}
else if(parola == 'piovere'){traduzione = 'elia'; significati = ''}
else if(parola == 'piovere'){traduzione = 'elia'; significati = ''}
else if(parola == 'piovere'){traduzione = 'shazank'; significati = ''}
else if(parola == 'piovoso'){traduzione = 'dim'; significati = ''}
else if(parola == 'piovoso'){traduzione = 'dim'; significati = ''}
else if(parola == 'piovuto'){traduzione = 'eliannen'; significati = ''}
else if(parola == 'piovuto'){traduzione = 'eliannen'; significati = ''}
else if(parola == 'più il là'){traduzione = 'athron'; significati = ''}
else if(parola == 'polline'){traduzione = 'mal'; significati = ''}
else if(parola == 'polline'){traduzione = 'mal'; significati = ''}
else if(parola == 'polvere'){traduzione = 'ast'; significati = ''}
else if(parola == 'polvere'){traduzione = 'ast'; significati = ''}
else if(parola == 'ponte'){traduzione = 'iant'; significati = ''}
else if(parola == 'ponte'){traduzione = 'iant'; significati = ''}
else if(parola == 'ponte'){traduzione = 'kerirh'; significati = ''}
else if(parola == 'popolo della costa'){traduzione = 'falathrim'; significati = ''}
else if(parola == 'popolo'){traduzione = 'gwaith'; significati = ''}
else if(parola == 'popolo'){traduzione = 'gwaith'; significati = ''}
else if(parola == 'porca'){traduzione = 'wazza'; significati = ''}
else if(parola == 'porto'){traduzione = 'lond'; significati = ''}
else if(parola == 'porto'){traduzione = 'lond'; significati = ''}
else if(parola == 'possente'){traduzione = 'beleg'; significati = ''}
else if(parola == 'possente'){traduzione = 'beleg'; significati = ''}
else if(parola == 'possesso'){traduzione = 'gared'; significati = ''}
else if(parola == 'possesso'){traduzione = 'gared'; significati = ''}
else if(parola == 'possessore'){traduzione = 'gardir'; significati = ''}
else if(parola == 'possessore'){traduzione = 'gardir'; significati = ''}
else if(parola == 'posto'){traduzione = 'sad'; significati = ''}
else if(parola == 'posto'){traduzione = 'sad'; significati = ''}
else if(parola == 'potere'){traduzione = 'bad'; significati = ''}
else if(parola == 'potere'){traduzione = 'bal'; significati = ''}
else if(parola == 'potere'){traduzione = 'rovhak'; significati = ''}
else if(parola == 'povero'){traduzione = 'hanye'; significati = ''}
else if(parola == 'povertà'){traduzione = 'hanyer'; significati = ''}
else if(parola == 'pozza'){traduzione = 'bith'; significati = ''}
else if(parola == 'pozza'){traduzione = 'both'; significati = ''}
else if(parola == 'pozzo'){traduzione = 'malakh'; significati = ''}
else if(parola == 'precipizio'){traduzione = 'rhass'; significati = ''}
else if(parola == 'precipizio'){traduzione = 'rhass'; significati = ''}
else if(parola == 'pregare'){traduzione = 'lannish'; significati = ''}
else if(parola == 'preghiera'){traduzione = 'egleraid'; significati = ''}
else if(parola == 'preghiera'){traduzione = 'egleriad'; significati = ''}
else if(parola == 'presa'){traduzione = 'mabed'; significati = ''}
else if(parola == 'presa'){traduzione = 'mabed'; significati = ''}
else if(parola == 'pretoggere'){traduzione = 'beria'; significati = ''}
else if(parola == 'prigione'){traduzione = 'band'; significati = ''}
else if(parola == 'prigione'){traduzione = 'band'; significati = ''}
else if(parola == 'prigione'){traduzione = 'hiirthus'; significati = ''}
else if(parola == 'primavera'){traduzione = 'ethuil'; significati = ''}
else if(parola == 'primavera'){traduzione = 'tuil'; significati = ''}
else if(parola == 'principe'){traduzione = 'cund'; significati = ''}
else if(parola == 'principe'){traduzione = 'cund'; significati = ''}
else if(parola == 'principe'){traduzione = 'haerim'; significati = ''}
else if(parola == 'principesco'){traduzione = 'harimsk'; significati = ''}
else if(parola == 'principessa'){traduzione = 'hearim'; significati = ''}
else if(parola == 'proteggente'){traduzione = 'beriol'; significati = ''}
else if(parola == 'proteggente'){traduzione = 'beriol'; significati = ''}
else if(parola == 'proteggere'){traduzione = 'beria'; significati = ''}
else if(parola == 'protetto'){traduzione = 'beriannen'; significati = ''}
else if(parola == 'protetto'){traduzione = 'beriannen'; significati = ''}
else if(parola == 'protettore'){traduzione = 'beriadir'; significati = ''}
else if(parola == 'protettore'){traduzione = 'beriadir'; significati = ''}
else if(parola == 'protezione'){traduzione = 'beriad'; significati = ''}
else if(parola == 'protezione'){traduzione = 'beriad'; significati = ''}
else if(parola == 'provare'){traduzione = 'dedidex'; significati = ''}
else if(parola == 'pugnale'){traduzione = 'exolh'; significati = ''}
else if(parola == 'pugnale'){traduzione = 'sigil'; significati = ''}
else if(parola == 'pugnale'){traduzione = 'sigil'; significati = ''}
else if(parola == 'pugno'){traduzione = 'paur'; significati = ''}
else if(parola == 'pugno'){traduzione = 'paur'; significati = ''}
else if(parola == 'pugno'){traduzione = 'pelkar'; significati = ''}
else if(parola == 'puledro'){traduzione = 'atitshoke'; significati = ''}
else if(parola == 'pungente'){traduzione = 'erchol'; significati = ''}
else if(parola == 'pungente'){traduzione = 'erchol'; significati = ''}
else if(parola == 'pungere'){traduzione = 'ercha'; significati = ''}
else if(parola == 'pungere'){traduzione = 'ercha'; significati = ''}
else if(parola == 'punta di lancia'){traduzione = 'thela'; significati = ''}
else if(parola == 'punta'){traduzione = 'aeg'; significati = ''}
else if(parola == 'punta'){traduzione = 'aeg'; significati = ''}
else if(parola == 'punto'){traduzione = 'erchannen'; significati = ''}
else if(parola == 'punto'){traduzione = 'erchannen'; significati = ''}
else if(parola == 'puntura'){traduzione = 'erchad'; significati = ''}
else if(parola == 'puntura'){traduzione = 'erchad'; significati = ''}
else if(parola == 'punzecchiare'){traduzione = 'eitha'; significati = ''}
else if(parola == 'quà'){traduzione = 'kia'; significati = ''}
else if(parola == 'quattro'){traduzione = 'canad'; significati = ''}
else if(parola == 'quercia'){traduzione = 'doron'; significati = ''}
else if(parola == 'quì'){traduzione = 'kio'; significati = ''}
else if(parola == 'rabbrividente'){traduzione = 'girith'; significati = ''}
else if(parola == 'rabbrividito'){traduzione = 'girnen'; significati = ''}
else if(parola == 'raccontante'){traduzione = 'trenarel'; significati = ''}
else if(parola == 'raccontanto'){traduzione = 'trenoren'; significati = ''}
else if(parola == 'raccontare'){traduzione = 'nara'; significati = ''}
else if(parola == 'raccontato'){traduzione = 'narnen'; significati = ''}
else if(parola == 'racconto'){traduzione = 'narn'; significati = ''}
else if(parola == 'radice commestibile'){traduzione = 'solch'; significati = ''}
else if(parola == 'radice'){traduzione = 'thond'; significati = ''}
else if(parola == 'radura'){traduzione = 'lant'; significati = ''}
else if(parola == 'raffica'){traduzione = 'gwam'; significati = ''}
else if(parola == 'ragazza'){traduzione = 'boheeka'; significati = ''}
else if(parola == 'ragazza'){traduzione = 'gwend'; significati = ''}
else if(parola == 'raggiante'){traduzione = 'faen'; significati = ''}
else if(parola == 'ragnatela'){traduzione = 'nath'; significati = ''}
else if(parola == 'ragno'){traduzione = 'lhingril'; significati = ''}
else if(parola == 'ramo'){traduzione = 'branch'; significati = ''}
else if(parola == 'rana'){traduzione = 'cabor'; significati = ''}
else if(parola == 'ranger'){traduzione = 'rovokh'; significati = ''}
else if(parola == 'rapido'){traduzione = 'lagor'; significati = ''}
else if(parola == 'ratto'){traduzione = 'nar'; significati = ''}
else if(parola == 'razza'){traduzione = 'neelix'; significati = ''}
else if(parola == 're'){traduzione = 'aran'; significati = ''}
else if(parola == 're'){traduzione = 'sk'; significati = ''}
else if(parola == 'reale'){traduzione = 'skaman'; significati = ''}
else if(parola == 'reame'){traduzione = 'aran'; significati = ''}
else if(parola == 'recingere'){traduzione = 'thora'; significati = ''}
else if(parola == 'recintato'){traduzione = 'thoren'; significati = ''}
else if(parola == 'recinto'){traduzione = 'ephel'; significati = ''}
else if(parola == 'recinzione'){traduzione = 'thorad'; significati = ''}
else if(parola == 'regalo'){traduzione = 'bache'; significati = ''}
else if(parola == 'reggimento'){traduzione = 'gweth'; significati = ''}
else if(parola == 'regina'){traduzione = 'hiri'; significati = ''}
else if(parola == 'regina'){traduzione = 'skcha'; significati = ''}
else if(parola == 'regione'){traduzione = 'aran'; significati = ''}
else if(parola == 'resistente'){traduzione = 'broniol'; significati = ''}
else if(parola == 'resistenza'){traduzione = 'broniad'; significati = ''}
else if(parola == 'resistere'){traduzione = 'bronia'; significati = ''}
else if(parola == 'resistito'){traduzione = 'broniannen'; significati = ''}
else if(parola == 'respirante'){traduzione = 'thuiol'; significati = ''}
else if(parola == 'respirare'){traduzione = 'thuia'; significati = ''}
else if(parola == 'respirato'){traduzione = 'thuiannen'; significati = ''}
else if(parola == 'respirazione'){traduzione = 'thuiad'; significati = ''}
else if(parola == 'restante'){traduzione = 'dorhol'; significati = ''}
else if(parola == 'restare'){traduzione = 'dortha'; significati = ''}
else if(parola == 'restato'){traduzione = 'dorthannen'; significati = ''}
else if(parola == 'ricchezza'){traduzione = 'hadar'; significati = ''}
else if(parola == 'ricciolo'){traduzione = 'loch'; significati = ''}
else if(parola == 'ricco'){traduzione = 'hada'; significati = ''}
else if(parola == 'richiamo'){traduzione = 'ganed'; significati = ''}
else if(parola == 'ridere'){traduzione = 'tomalk'; significati = ''}
else if(parola == 'riempiente'){traduzione = 'pathrol'; significati = ''}
else if(parola == 'riempimento'){traduzione = 'pathrad'; significati = ''}
else if(parola == 'riempire'){traduzione = 'pathra'; significati = ''}
else if(parola == 'riempito'){traduzione = 'pathrannen'; significati = ''}
else if(parola == 'rilasciante'){traduzione = 'leithol'; significati = ''}
else if(parola == 'rilasciare'){traduzione = 'leitha'; significati = ''}
else if(parola == 'rilasciato'){traduzione = 'leithian'; significati = ''}
else if(parola == 'riparare'){traduzione = 'altha'; significati = ''}
else if(parola == 'riparato'){traduzione = 'halthannen'; significati = ''}
else if(parola == 'riparo'){traduzione = 'esgal'; significati = ''}
else if(parola == 'risoluto'){traduzione = 'brond'; significati = ''}
else if(parola == 'risplendente'){traduzione = 'silol'; significati = ''}
else if(parola == 'risplendere'){traduzione = 'sila'; significati = ''}
else if(parola == 'risveglio'){traduzione = 'cuivros'; significati = ''}
else if(parola == 'riunione'){traduzione = 'aderthad'; significati = ''}
else if(parola == 'riunito'){traduzione = 'aderthannen'; significati = ''}
else if(parola == 'riva'){traduzione = 'rast'; significati = ''}
else if(parola == 'robusto'){traduzione = 'thala'; significati = ''}
else if(parola == 'rondine'){traduzione = 'tuilin'; significati = ''}
else if(parola == 'rosso'){traduzione = 'caran'; significati = ''}
else if(parola == 'rovina'){traduzione = 'hubutnaza'; significati = ''}
else if(parola == 'rubicondo'){traduzione = 'crann'; significati = ''}
else if(parola == 'rumore'){traduzione = 'su'; significati = ''}
else if(parola == 'runa'){traduzione = 'certh'; significati = ''}
else if(parola == 'ruota'){traduzione = 'norn'; significati = ''}
else if(parola == 'saggio'){traduzione = 'bajor'; significati = ''}
else if(parola == 'saggio'){traduzione = 'golwen'; significati = ''}
else if(parola == 'sala'){traduzione = 'tham'; significati = ''}
else if(parola == 'salice'){traduzione = 'tathor'; significati = ''}
else if(parola == 'salire'){traduzione = 'amra'; significati = ''}
else if(parola == 'saltante'){traduzione = 'cabel'; significati = ''}
else if(parola == 'saltare'){traduzione = 'bokarh'; significati = ''}
else if(parola == 'saltare'){traduzione = 'cab'; significati = ''}
else if(parola == 'saltare'){traduzione = 'cammen'; significati = ''}
else if(parola == 'saltatore'){traduzione = 'cabir'; significati = ''}
else if(parola == 'saltellante'){traduzione = 'labor'; significati = ''}
else if(parola == 'saltellare'){traduzione = 'laba'; significati = ''}
else if(parola == 'saltellato'){traduzione = 'lamen'; significati = ''}
else if(parola == 'saltello'){traduzione = 'labad'; significati = ''}
else if(parola == 'salto'){traduzione = 'cabed'; significati = ''}
else if(parola == 'salutante'){traduzione = 'suillanol'; significati = ''}
else if(parola == 'salutare'){traduzione = 'suillana'; significati = ''}
else if(parola == 'salutato'){traduzione = 'suillanen'; significati = ''}
else if(parola == 'saluto'){traduzione = 'suillanad'; significati = ''}
else if(parola == 'salvare'){traduzione = 'karahd'; significati = ''}
else if(parola == 'salvo'){traduzione = 'karah'; significati = ''}
else if(parola == 'sangue'){traduzione = 'iàr'; significati = ''}
else if(parola == 'sapere'){traduzione = 'sakharov'; significati = ''}
else if(parola == 'sapiente'){traduzione = 'istir'; significati = ''}
else if(parola == 'sbagliare'){traduzione = 'neitha'; significati = ''}
else if(parola == 'sbagliato'){traduzione = 'neithannen'; significati = ''}
else if(parola == 'sbaglio'){traduzione = 'neithad'; significati = ''}
else if(parola == 'sbattente'){traduzione = 'blabel'; significati = ''}
else if(parola == 'sbattere'){traduzione = 'blab'; significati = ''}
else if(parola == 'sbattimento'){traduzione = 'blabed'; significati = ''}
else if(parola == 'sbattuto'){traduzione = 'blammen'; significati = ''}
else if(parola == 'sbiadimento'){traduzione = 'thinnad'; significati = ''}
else if(parola == 'sbiadire'){traduzione = 'thinna'; significati = ''}
else if(parola == 'sbiadito'){traduzione = 'thinned'; significati = ''}
else if(parola == 'sbiancante'){traduzione = 'nimmidolo'; significati = ''}
else if(parola == 'sbiancare'){traduzione = 'nimmida'; significati = ''}
else if(parola == 'sbiancata'){traduzione = 'nimmidad'; significati = ''}
else if(parola == 'sbiancato'){traduzione = 'nimminen'; significati = ''}
else if(parola == 'scaldare'){traduzione = 'ur'; significati = ''}
else if(parola == 'scavante'){traduzione = 'rostol'; significati = ''}
else if(parola == 'scavare'){traduzione = 'rosta'; significati = ''}
else if(parola == 'scavato'){traduzione = 'rostannen'; significati = ''}
else if(parola == 'scavatore'){traduzione = 'rostir'; significati = ''}
else if(parola == 'scavo'){traduzione = 'rostad'; significati = ''}
else if(parola == 'scendere'){traduzione = 'amra'; significati = ''}
else if(parola == 'schiaffo'){traduzione = 'lakir'; significati = ''}
else if(parola == 'schiuma'){traduzione = 'falf'; significati = ''}
else if(parola == 'schiumante'){traduzione = 'falthol'; significati = ''}
else if(parola == 'schiumare'){traduzione = 'faltha'; significati = ''}
else if(parola == 'schiumato'){traduzione = 'falthannen'; significati = ''}
else if(parola == 'scintilla'){traduzione = 'tinu'; significati = ''}
else if(parola == 'scintillante'){traduzione = 'tinnol'; significati = ''}
else if(parola == 'scintillare'){traduzione = 'gil'; significati = ''}
else if(parola == 'scintillare'){traduzione = 'tinna'; significati = ''}
else if(parola == 'scintillato'){traduzione = 'tinned'; significati = ''}
else if(parola == 'scintillio'){traduzione = 'tinnad'; significati = ''}
else if(parola == 'scomparire'){traduzione = 'fir'; significati = ''}
else if(parola == 'scomparsa'){traduzione = 'fired'; significati = ''}
else if(parola == 'scomparso'){traduzione = 'firnen'; significati = ''}
else if(parola == 'scorrere'){traduzione = 'rimma/siria'; significati = ''}
else if(parola == 'scorso'){traduzione = 'rimmanen'; significati = ''}
else if(parola == 'scrittore'){traduzione = 'teithil'; significati = ''}
else if(parola == 'scudo'){traduzione = 'gokor'; significati = ''}
else if(parola == 'scuro'){traduzione = 'doll'; significati = ''}
else if(parola == 'scuro'){traduzione = 'werix'; significati = ''}
else if(parola == 'secco'){traduzione = 'parch'; significati = ''}
else if(parola == 'secondo'){traduzione = 'be'; significati = ''}
else if(parola == 'segreto'){traduzione = 'kosel'; significati = ''}
else if(parola == 'seguente'){traduzione = 'aphadol'; significati = ''}
else if(parola == 'seguire'){traduzione = 'aphada'; significati = ''}
else if(parola == 'seguito'){traduzione = 'aphannen'; significati = ''}
else if(parola == 'sei'){traduzione = 'eneg'; significati = ''}
else if(parola == 'semina'){traduzione = 'radhed'; significati = ''}
else if(parola == 'seminare'){traduzione = 'redh'; significati = ''}
else if(parola == 'seminato'){traduzione = 'rennen'; significati = ''}
else if(parola == 'sempre'){traduzione = 'ui'; significati = ''}
else if(parola == 'semprebianco'){traduzione = 'uilos'; significati = ''}
else if(parola == 'sensuale'){traduzione = 'maraud'; significati = ''}
else if(parola == 'sentiero'){traduzione = 'taloth'; significati = ''}
else if(parola == 'sera'){traduzione = 'thin'; significati = ''}
else if(parola == 'serpente di mare'){traduzione = 'limlug'; significati = ''}
else if(parola == 'serpente'){traduzione = 'lym'; significati = ''}
else if(parola == 'servente'){traduzione = 'buiol'; significati = ''}
else if(parola == 'servire'){traduzione = 'buia'; significati = ''}
else if(parola == 'servito'){traduzione = 'buiannen'; significati = ''}
else if(parola == 'servitù'){traduzione = 'buiad'; significati = ''}
else if(parola == 'servo'){traduzione = 'buiadir'; significati = ''}
else if(parola == 'sesso'){traduzione = 'sakha'; significati = ''}
else if(parola == 'sette'){traduzione = 'odo'; significati = ''}
else if(parola == 'settembre'){traduzione = 'ivanneth'; significati = ''}
else if(parola == 'settentrionale'){traduzione = 'fornen'; significati = ''}
else if(parola == 'sfortuna'){traduzione = 'nolek'; significati = ''}
else if(parola == 'sfortunato'){traduzione = 'kolekor'; significati = ''}
else if(parola == 'sguardo'){traduzione = 'palan-dired'; significati = ''}
else if(parola == 'si'){traduzione = 'is'; significati = ''}
else if(parola == 'si'){traduzione = 'leh'; significati = ''}
else if(parola == 'signora'){traduzione = 'brennil'; significati = ''}
else if(parola == 'signore dei cavalli'){traduzione = 'rochir'; significati = ''}
else if(parola == 'signore'){traduzione = 'brannon'; significati = ''}
else if(parola == 'signore'){traduzione = 'tur'; significati = ''}
else if(parola == 'silenzio'){traduzione = 'din'; significati = ''}
else if(parola == 'silenzioso'){traduzione = 'diner'; significati = ''}
else if(parola == 'silmaril'){traduzione = 'silevril'; significati = ''}
else if(parola == 'simpatico'){traduzione = 'korby'; significati = ''}
else if(parola == 'sindaco'){traduzione = 'condir'; significati = ''}
else if(parola == 'sinistra'){traduzione = 'crunn'; significati = ''}
else if(parola == 'sinistra'){traduzione = 'hair'; significati = ''}
else if(parola == 'sistemare'){traduzione = 'partha'; significati = ''}
else if(parola == 'sistemato'){traduzione = 'parthannen'; significati = ''}
else if(parola == 'sistemazione'){traduzione = 'parthad'; significati = ''}
else if(parola == 'sofferente'){traduzione = 'veneh'; significati = ''}
else if(parola == 'soffio'){traduzione = 'sultha'; significati = ''}
else if(parola == 'soffrire'){traduzione = 'venelh'; significati = ''}
else if(parola == 'soglia'){traduzione = 'fend'; significati = ''}
else if(parola == 'sognante'){traduzione = 'olthol'; significati = ''}
else if(parola == 'sognare'){traduzione = 'oltha'; significati = ''}
else if(parola == 'sognato'){traduzione = 'olthannen'; significati = ''}
else if(parola == 'sognatore'){traduzione = 'olthir'; significati = ''}
else if(parola == 'sogno'){traduzione = 'òl'; significati = ''}
else if(parola == 'sole'){traduzione = 'anor'; significati = ''}
else if(parola == 'sole'){traduzione = 'bryenh'; significati = ''}
else if(parola == 'solitario'){traduzione = 'ereb'; significati = ''}
else if(parola == 'solitario'){traduzione = 'rixh'; significati = ''}
else if(parola == 'somma'){traduzione = 'gonoded'; significati = ''}
else if(parola == 'sommante'){traduzione = 'gonodel'; significati = ''}
else if(parola == 'sommare'){traduzione = 'gonod'; significati = ''}
else if(parola == 'sommato'){traduzione = 'gononnen'; significati = ''}
else if(parola == 'sopra'){traduzione = 'erin'; significati = ''}
else if(parola == 'soprannome'){traduzione = 'glamoth'; significati = ''}
else if(parola == 'sopravvissuto'){traduzione = 'brondir'; significati = ''}
else if(parola == 'sopravvissuto'){traduzione = 'bronnen'; significati = ''}
else if(parola == 'sopravvivente'){traduzione = 'bronod'; significati = ''}
else if(parola == 'sopravvivenza'){traduzione = 'bronal'; significati = ''}
else if(parola == 'sopravvivere'){traduzione = 'brona'; significati = ''}
else if(parola == 'sorella'){traduzione = 'helas'; significati = ''}
else if(parola == 'sorella'){traduzione = 'muinthel'; significati = ''}
else if(parola == 'sorte'){traduzione = 'amarth'; significati = ''}
else if(parola == 'sorvegliante'){traduzione = 'tirith'; significati = ''}
else if(parola == 'sorveglianza'){traduzione = 'tired'; significati = ''}
else if(parola == 'sorvegliato'){traduzione = 'tirnen'; significati = ''}
else if(parola == 'sottile'){traduzione = 'nind'; significati = ''}
else if(parola == 'sotto'){traduzione = 'di'; significati = ''}
else if(parola == 'spaccante'){traduzione = 'narchol'; significati = ''}
else if(parola == 'spaccare attraverso'){traduzione = 'hasta'; significati = ''}
else if(parola == 'spaccare'){traduzione = 'drava'; significati = ''}
else if(parola == 'spaccato attraverso'){traduzione = 'hastammen'; significati = ''}
else if(parola == 'spaccato'){traduzione = 'drammen'; significati = ''}
else if(parola == 'spaccatura attravero'){traduzione = 'hastad'; significati = ''}
else if(parola == 'spaccatura'){traduzione = 'narchad'; significati = ''}
else if(parola == 'spacco'){traduzione = 'dravad'; significati = ''}
else if(parola == 'spada'){traduzione = 'megil'; significati = ''}
else if(parola == 'spada'){traduzione = 'mekh'; significati = ''}
else if(parola == 'spadaccino'){traduzione = 'magor'; significati = ''}
else if(parola == 'spargere'){traduzione = 'pelia'; significati = ''}
else if(parola == 'spargimento'){traduzione = 'peliad'; significati = ''}
else if(parola == 'sparso'){traduzione = 'peliannen'; significati = ''}
else if(parola == 'spegnere'){traduzione = 'luithia'; significati = ''}
else if(parola == 'spegnimento'){traduzione = 'luithiad'; significati = ''}
else if(parola == 'spento'){traduzione = 'luithiannen'; significati = ''}
else if(parola == 'speranza'){traduzione = 'estel'; significati = ''}
else if(parola == 'sperare'){traduzione = 'hartha'; significati = ''}
else if(parola == 'sperare'){traduzione = 'yshillyam'; significati = ''}
else if(parola == 'sperato'){traduzione = 'harthannen'; significati = ''}
else if(parola == 'spesso'){traduzione = 'tug'; significati = ''}
else if(parola == 'spettacolo'){traduzione = 'khalisse'; significati = ''}
else if(parola == 'spia'){traduzione = 'ethir'; significati = ''}
else if(parola == 'spiaggia'){traduzione = 'habad'; significati = ''}
else if(parola == 'splendore'){traduzione = 'claur'; significati = ''}
else if(parola == 'sporcare'){traduzione = 'gwatha'; significati = ''}
else if(parola == 'sporcato'){traduzione = 'gwathannen'; significati = ''}
else if(parola == 'sporco'){traduzione = 'gwathad'; significati = ''}
else if(parola == 'sposa'){traduzione = 'dis'; significati = ''}
else if(parola == 'spronamento'){traduzione = 'horthad'; significati = ''}
else if(parola == 'spronare'){traduzione = 'hortha'; significati = ''}
else if(parola == 'spronato'){traduzione = 'horthannen'; significati = ''}
else if(parola == 'spruzzo'){traduzione = 'rys'; significati = ''}
else if(parola == 'spugna'){traduzione = 'hwand'; significati = ''}
else if(parola == 'sputare'){traduzione = 'puia'; significati = ''}
else if(parola == 'sputato'){traduzione = 'puiannen'; significati = ''}
else if(parola == 'sputo'){traduzione = 'puiad'; significati = ''}
else if(parola == 'srenate'){traduzione = 'kardes'; significati = ''}
else if(parola == 'stagno'){traduzione = 'lin'; significati = ''}
else if(parola == 'stallone'){traduzione = 'aetmeshfie'; significati = ''}
else if(parola == 'stare'){traduzione = 'hebram'; significati = ''}
else if(parola == 'stella'){traduzione = 'gil'; significati = ''}
else if(parola == 'stelle'){traduzione = 'giliath'; significati = ''}
else if(parola == 'storto'){traduzione = 'raen'; significati = ''}
else if(parola == 'strada'){traduzione = 'rath'; significati = ''}
else if(parola == 'strano'){traduzione = 'eymorg'; significati = ''}
else if(parola == 'strappare'){traduzione = 'ritha'; significati = ''}
else if(parola == 'strappato'){traduzione = 'rithannen'; significati = ''}
else if(parola == 'strappo'){traduzione = 'rithad'; significati = ''}
else if(parola == 'strattone'){traduzione = 'rinc'; significati = ''}
else if(parola == 'stregone'){traduzione = 'gollor'; significati = ''}
else if(parola == 'stregone'){traduzione = 'ithron'; significati = ''}
else if(parola == 'su'){traduzione = 'am'; significati = ''}
else if(parola == 'succo'){traduzione = 'saw'; significati = ''}
else if(parola == 'sud'){traduzione = 'harad'; significati = ''}
else if(parola == 'suo'){traduzione = 'din'; significati = ''}
else if(parola == 'suolo'){traduzione = 'talaf'; significati = ''}
else if(parola == 'suonare'){traduzione = 'gann'; significati = ''}
else if(parola == 'suonato'){traduzione = 'nellanen'; significati = ''}
else if(parola == 'suonatore'){traduzione = 'talagan'; significati = ''}
else if(parola == 'suono'){traduzione = 'glinn'; significati = ''}
else if(parola == 'sussurro'){traduzione = 'lhoss'; significati = ''}
else if(parola == 'svegliare'){traduzione = 'nokvin'; significati = ''}
else if(parola == 'svestire'){traduzione = 'heltha'; significati = ''}
else if(parola == 'svestito'){traduzione = 'helthannen'; significati = ''}
else if(parola == 'tagliare'){traduzione = 'osgar'; significati = ''}
else if(parola == 'tagliato'){traduzione = 'osgarnen'; significati = ''}
else if(parola == 'tagliente'){traduzione = 'maeg'; significati = ''}
else if(parola == 'taglio'){traduzione = 'rest'; significati = ''}
else if(parola == 'taverna'){traduzione = 'sarge'; significati = ''}
else if(parola == 'te'){traduzione = 'et'; significati = ''}
else if(parola == 'tela'){traduzione = 'lhing'; significati = ''}
else if(parola == 'tempesta'){traduzione = 'alagos'; significati = ''}
else if(parola == 'tempo'){traduzione = 'krhon'; significati = ''}
else if(parola == 'tempo'){traduzione = 'lu'; significati = ''}
else if(parola == 'tenebra'){traduzione = 'mor'; significati = ''}
else if(parola == 'tenere'){traduzione = 'gar'; significati = ''}
else if(parola == 'tenue'){traduzione = 'malu'; significati = ''}
else if(parola == 'tenuta'){traduzione = 'hebed'; significati = ''}
else if(parola == 'tenuto'){traduzione = 'hemmen'; significati = ''}
else if(parola == 'terra di mezzo'){traduzione = 'Ennor'; significati = ''}
else if(parola == 'terra'){traduzione = 'atosh'; significati = ''}
else if(parola == 'terra'){traduzione = 'dor'; significati = ''}
else if(parola == 'territorio'){traduzione = 'ostar'; significati = ''}
else if(parola == 'terrore'){traduzione = 'gruithad'; significati = ''}
else if(parola == 'terrorizzante'){traduzione = 'ruithol'; significati = ''}
else if(parola == 'terrorizzare'){traduzione = 'gruithannen'; significati = ''}
else if(parola == 'terrorizzato'){traduzione = 'gruitha'; significati = ''}
else if(parola == 'ti'){traduzione = 'it'; significati = ''}
else if(parola == 'tiepido'){traduzione = 'laug'; significati = ''}
else if(parola == 'tigre'){traduzione = 'raorsh'; significati = ''}
else if(parola == 'timore'){traduzione = 'gaer'; significati = ''}
else if(parola == 'tirannico'){traduzione = 'baug'; significati = ''}
else if(parola == 'tiranno'){traduzione = 'bauglir'; significati = ''}
else if(parola == 'tomba'){traduzione = 'sarch'; significati = ''}
else if(parola == 'tormentante'){traduzione = 'trastol'; significati = ''}
else if(parola == 'tormentare'){traduzione = 'trasta'; significati = ''}
else if(parola == 'tormentato'){traduzione = 'trastannen'; significati = ''}
else if(parola == 'tormentatore'){traduzione = 'trastir'; significati = ''}
else if(parola == 'tormento'){traduzione = 'trastad'; significati = ''}
else if(parola == 'toro'){traduzione = 'strikt'; significati = ''}
else if(parola == 'torre'){traduzione = 'barad'; significati = ''}
else if(parola == 'torrente'){traduzione = 'homx'; significati = ''}
else if(parola == 'torretta'){traduzione = 'tirion'; significati = ''}
else if(parola == 'torta'){traduzione = 'cram'; significati = ''}
else if(parola == 'tra'){traduzione = 'im'; significati = ''}
else if(parola == 'traccia'){traduzione = 'teithad'; significati = ''}
else if(parola == 'tracciante'){traduzione = 'teithod'; significati = ''}
else if(parola == 'tracciare'){traduzione = 'theida'; significati = ''}
else if(parola == 'tracciato'){traduzione = 'theidannen'; significati = ''}
else if(parola == 'tradimento'){traduzione = 'gweriad'; significati = ''}
else if(parola == 'tradire'){traduzione = 'gweria'; significati = ''}
else if(parola == 'tradito'){traduzione = 'gweriannen'; significati = ''}
else if(parola == 'traditore'){traduzione = 'gweriadir'; significati = ''}
else if(parola == 'tradizione'){traduzione = 'golu'; significati = ''}
else if(parola == 'traghettatore'){traduzione = 'athl'; significati = ''}
else if(parola == 'tre'){traduzione = 'neled'; significati = ''}
else if(parola == 'treccia'){traduzione = 'finn'; significati = ''}
else if(parola == 'triangolo'){traduzione = 'naith'; significati = ''}
else if(parola == 'triste'){traduzione = 'nurn'; significati = ''}
else if(parola == 'troll'){traduzione = 'torog'; significati = ''}
else if(parola == 'trovare'){traduzione = 'rada'; significati = ''}
else if(parola == 'trovato'){traduzione = 'radannen'; significati = ''}
else if(parola == 'truppa'){traduzione = 'herth'; significati = ''}
else if(parola == 'tu'){traduzione = 'uth'; significati = ''}
else if(parola == 'tumulo'){traduzione = 'haudh'; significati = ''}
else if(parola == 'tuono'){traduzione = 'kazam'; significati = ''}
else if(parola == 'turbare'){traduzione = 'prestannen'; significati = 'sinonimi: disturbare, afflito, preoccupato, turbato,disturbato'}
else if(parola == 'uccellino'){traduzione = 'aew'; significati = ''}
else if(parola == 'uccello'){traduzione = 'misk'; significati = ''}
else if(parola == 'uccidere'){traduzione = 'jillabh'; significati = ''}
else if(parola == 'uccisione'){traduzione = 'daged'; significati = ''}
else if(parola == 'ucciso'){traduzione = 'dangen'; significati = ''}
else if(parola == 'ultimo'){traduzione = 'medui'; significati = ''}
else if(parola == 'ululante'){traduzione = 'gawol'; significati = ''}
else if(parola == 'ululare'){traduzione = 'gawa'; significati = ''}
else if(parola == 'ululato'){traduzione = 'gonen'; significati = ''}
else if(parola == 'umano'){traduzione = 'garak'; significati = ''}
else if(parola == 'umido'){traduzione = 'limp'; significati = ''}
else if(parola == 'un'){traduzione = 'On'; significati = ''}
else if(parola == 'una'){traduzione = 'onar'; significati = ''}
else if(parola == 'unente'){traduzione = 'erthol'; significati = ''}
else if(parola == 'unione'){traduzione = 'erthad'; significati = ''}
else if(parola == 'unire'){traduzione = 'ertha'; significati = ''}
else if(parola == 'unito'){traduzione = 'erthannen'; significati = ''}
else if(parola == 'uno'){traduzione = 'min'; significati = ''}
else if(parola == 'uno'){traduzione = 'onor'; significati = ''}
else if(parola == 'uomini delle nevi'){traduzione = 'lossoth'; significati = ''}
else if(parola == 'uomo'){traduzione = 'dir'; significati = ''}
else if(parola == 'uomo'){traduzione = 'dunadan'; significati = ''}
else if(parola == 'uomo'){traduzione = 'irdio'; significati = ''}
else if(parola == 'usare'){traduzione = 'iuitha'; significati = ''}
else if(parola == 'usato'){traduzione = 'iuithannen'; significati = ''}
else if(parola == 'usignolo'){traduzione = 'dùlinn'; significati = ''}
else if(parola == 'uso'){traduzione = 'iuitad'; significati = ''}
else if(parola == 'utile'){traduzione = 'maer'; significati = ''}
else if(parola == 'vagabondaggio'){traduzione = 'raned'; significati = ''}
else if(parola == 'vagabondare'){traduzione = 'ran'; significati = ''}
else if(parola == 'vagabondato'){traduzione = 'rannen'; significati = ''}
else if(parola == 'valle'){traduzione = 'nan'; significati = ''}
else if(parola == 'varco'){traduzione = 'faug'; significati = ''}
else if(parola == 'vasaio'){traduzione = 'cennan'; significati = ''}
else if(parola == 'vecchio'){traduzione = 'brun'; significati = ''}
else if(parola == 'vedente'){traduzione = 'cenel'; significati = ''}
else if(parola == 'vedere'){traduzione = 'cen'; significati = ''}
else if(parola == 'veleno'){traduzione = 'saew'; significati = ''}
else if(parola == 'veloce'){traduzione = 'tuvok'; significati = ''}
else if(parola == 'venditore ambulante'){traduzione = 'bachor bechyr'; significati = ''}
else if(parola == 'venditore'){traduzione = 'bachor'; significati = ''}
else if(parola == 'venire'){traduzione = 'melurnh'; significati = ''}
else if(parola == 'venire'){traduzione = 'tol'; significati = ''}
else if(parola == 'vento'){traduzione = 'gwa'; significati = ''}
else if(parola == 'venuta'){traduzione = 'toled'; significati = ''}
else if(parola == 'venuto'){traduzione = 'tollen'; significati = ''}
else if(parola == 'verde'){traduzione = 'calen'; significati = ''}
else if(parola == 'vespro'){traduzione = 'aduial/minuial'; significati = ''}
else if(parola == 'vestire'){traduzione = 'ham'; significati = ''}
else if(parola == 'vestito'){traduzione = 'hammen'; significati = ''}
else if(parola == 'vestizione'){traduzione = 'habed'; significati = ''}
else if(parola == 'vestro'){traduzione = 'hele'; significati = ''}
else if(parola == 'via'){traduzione = 'men'; significati = ''}
else if(parola == 'viaggiare'){traduzione = 'padir'; significati = ''}
else if(parola == 'viandante'){traduzione = 'randir'; significati = ''}
else if(parola == 'vietare'){traduzione = 'boda'; significati = ''}
else if(parola == 'vietatp'){traduzione = 'bodannen'; significati = ''}
else if(parola == 'villaggio'){traduzione = 'per'; significati = ''}
else if(parola == 'vincolo'){traduzione = 'gwedh'; significati = ''}
else if(parola == 'vino'){traduzione = 'wayne'; significati = ''}
else if(parola == 'viso'){traduzione = 'baxz'; significati = ''}
else if(parola == 'vista'){traduzione = 'ceder'; significati = ''}
else if(parola == 'visto'){traduzione = 'tirad'; significati = ''}
else if(parola == 'vita'){traduzione = 'cennen'; significati = ''}
else if(parola == 'vita'){traduzione = 'velar'; significati = ''}
else if(parola == 'vitello'){traduzione = 'keanters'; significati = ''}
else if(parola == 'vivente'){traduzione = 'cuil'; significati = ''}
else if(parola == 'vivere'){traduzione = 'cuia'; significati = ''}
else if(parola == 'vivere'){traduzione = 'velarm'; significati = ''}
else if(parola == 'vivo'){traduzione = 'cuiannen'; significati = ''}
else if(parola == 'voi'){traduzione = 'ov'; significati = ''}
else if(parola == 'voi'){traduzione = 'ov'; significati = ''}
else if(parola == 'volante'){traduzione = 'reviol'; significati = ''}
else if(parola == 'volare'){traduzione = 'yatel'; significati = ''}
else if(parola == 'volato'){traduzione = 'reviannen'; significati = ''}
else if(parola == 'volere'){traduzione = 'prasch'; significati = ''}
else if(parola == 'volo'){traduzione = 'reviad'; significati = ''}
else if(parola == 'vuoto'){traduzione = 'caun'; significati = ''}
else if(parola == 'zampa'){traduzione = 'car'; significati = ''}
else if(parola == 'zanna'){traduzione = 'pod'; significati = ''}
else if(parola == 'zuppa'){traduzione = 'salph'; significati = ''}





else{alert('...non esiste questa parola nel linguaggio elfico!!!'); 
}

    document.getElementById("traduzione").innerHTML = traduzione;
    window.scrollBy(0, 180);
}